### ISSUE TITLE
adding a filter to query not returning result

### ISSUE THREAD

**Issue by robwilde** [vgrem/phpSPO#10]
wondering if you have used filters in any queries as when I add a filter, like below, there is no result.

`$query = '$select=ClientJobNumber,ID,ClientJobNumber,ClientPassword,ClientUserName,ClientUserName,ClientsFirstName,ClientsLastName';

$filter = '?$filter=ClientJobNumber eq \'56654\'';`

If I run only the query everything works fine. I have also tested the query with the filter using REST API tester and everything works great

**Comment by vgrem** [comment]
Greetings!

**Currently** the SDK supports the query options listed in [OData system query options using the OData endpoint](https://msdn.microsoft.com/en-us/library/gg309461(v=crm.7).aspx) MSDN page.

 
# Examples

Example 2. How to select only a specific set of fields(properties) for list items

```
$items = $list->getItems()->select('ClientJobNumber,ID,ClientPassword,ClientUserName,ClientUserName,ClientsFirstName,ClientsLastName');  //apply select query option
$ctx->load($items);
$ctx->executeQuery();
foreach( $items->getData() as $item ) {
    print "Task: {$item->ClientJobNumber}\r\n";
}

```

Example 3. How to find a specific list item(s) 

```
$items = $list->getItems()->filter("ClientJobNumber eq '56654'");  //apply filter query option
$ctx->load($items);
$ctx->executeQuery();
foreach( $items->getData() as $item ) {
	print "Task: '{$item->ClientJobNumber}'\r\n";
}

```


Please follow [listitem_examples.php](https://github.com/vgrem/phpSPO/blob/master/examples/listitem_examples.php) for a more examples.
