### ISSUE TITLE
Query parameter with spaces results in an error

### ISSUE THREAD

**Issue by wihab01** [vgrem/phpSPO#100]
Query parameter values with spaces are not correctly encoded when creating the request.
E.g. $title = "My list"; $lists->getByTitle($title) results in an HTTP Error 400 (Bad request) while $lists->getByTitle(rawurlencode($title)) works fine. So as a workaround I can encode values before using them, but I think that should be handled inside the library. Thus anybody know where it should be done?

**Comment by agamayaservers** [comment]
I was helped by using the InternalName parameter instead of the Title and methods using this parameter

**Comment by wihab01** [comment]
There may be several workarounds available.
But I think when a method getByTitle() is provided, than it should work with title and a title can have spaces. So I would call it a bug.

**Comment by vgrem** [comment]
Greetings!

Indeed it was a bug, thanks for catching this up!
OData (SharePoint REST) requires white spaces to be encoded, now its been resolved, please make sure to get the latest version.

Vadim
