### ISSUE TITLE
get specific list issue

### ISSUE THREAD

**Issue by uswross** [vgrem/phpSPO#103]
Hello,

I am having trouble getting a specific list from sharepoint. I tried the example and I also tried the following:
 

>        $listTitle = 'Archive 2017';
>        $list = $this->web->getLists()->getByTitle($listTitle);
>        $this->ctx->load($list);
>        $this->ctx->executeQuery();

Troubleshooting the response I get is:

> <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
> <HTML><HEAD><TITLE>Bad Request</TITLE>
> <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
> <BODY><h2>Bad Request</h2>
> <hr><p>HTTP Error 400. The request is badly formed.</p>
> </BODY></HTML>

However this is caught at a much later point in the library as a warning but then nothing works:

> Severity: Warning
> 
> Message: First parameter must either be an object or the name of an existing class
> 
> Filename: OData/JsonPayloadSerializer.php
> 
> Line Number: 52
> 
> Backtrace:
> 
> File: /var/www/html/application/third_party/phpSPO/src/Runtime/OData/JsonPayloadSerializer.php
> Line: 52
> Function: property_exists
> 
> File: /var/www/html/application/third_party/phpSPO/src/Runtime/ClientRequest.php
> Line: 150
> Function: deserialize
> 
> File: /var/www/html/application/third_party/phpSPO/src/Runtime/ClientRuntimeContext.php
> Line: 129
> Function: executeQuery
> 
> File: /var/www/html/application/third_party/phpSPO/src/SharePoint/ClientContext.php
> Line: 83
> Function: executeQuery
>

**Comment by vgrem** [comment]
Greetings!

Thanks for catching this issue, i was able to reproduce it.
OData (SharePoint REST) requires white spaces to be encoded, now its been resolved, please make sure to get the latest version. 

Vadim
