### ISSUE TITLE
Set directory & file permissions

### ISSUE THREAD

**Issue by dhrobinson** [vgrem/phpSPO#105]
Hi, is it possible to set rights on a file or a folder?
I have some code creating a folder and uploading a file, but I need to secure it, and set access only to specific users (email addresses).

**Comment by dhrobinson** [comment]
Can you confirm if this functionality exists in the API or not?

**Comment by vgrem** [comment]
Just came across this unanswered post and probably not apparently not relevant any longer , but anyway better late than never.

Assigning permissions per folder/file consists of two steps:

- create unique role assignments for the securable object(e.g file)  via `SecurableObject.BreakRoleInheritance` method ([doc](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee545470(v%3Doffice.15)))

- add/remove the role assignment on the securable object via `RoleAssignmentCollection.addRoleAssignment` method ([doc](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-visio/jj245278(v%3Doffice.15)))

### Example

```
$folder = $context->getWeb()->getFolderByServerRelativeUrl($folderUrl);
//1. create unique perms
$folderItem->breakRoleInheritance(true);
$context->executeQuery();
//2. grant read permissions for a group
$visitorGroup = self::$context->getWeb()->getAssociatedVisitorGroup();
$roleDef = self::$context->getWeb()->getRoleDefinitions()->getByType(RoleType::Reader);
$context->load($roleDef);
$context->load($visitorGroup);
$context->executeQuery();
$folderItem->getRoleAssignments()->addRoleAssignment($visitorGroup->getId(),$roleDef->getId());
$context->executeQuery();
```

Same applies for a file resource.  

### References

[How to: Work with Roles](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ee535915(v%3Doffice.14))
