### ISSUE TITLE
File Metatags

### ISSUE THREAD

**Issue by rs-dhansen** [vgrem/phpSPO#113]
Hi,

i have following problem with phpspo Sharepoint API.

added dynamic metatag (property) "articleNr" (with Number 123) to file as ListItem manually.
If i receive via ListItem the file i receive the property [articleNr] => "123"

But via getFileByServerRelativeUrl (current url https..... to file) its not possible to see the property "articleNr".

Can you modify your code to close this issue?

**Comment by koltyakov** [comment]
Hey @rs-dhansen, 

In SharePoint REST API, when getting a file with `getFileByServerRelativeUrl` the file object is retrieved. Not associated item.

`listItemAllFields` provides file's item metadata. Can be consumed using these endpoints:

- `/_api/web/getFileByServerRelativeUrl('PATH_TO_FILE')/listItemAllFields`
- `/_api/web/getFileByServerRelativeUrl('PATH_TO_FILE')?$expand=listItemAllFields`

I believe that select/expand functionality is already there so nothing to change on a lib side.

**Comment by rs-dhansen** [comment]
You right,

i make mistake, after getListItemAllFields i needed to make
$ctx->load($listEntity);
$ctx->executeQuery();

THX for your fast answer

**Comment by vgrem** [comment]
I propose to close since it was resolved
