### ISSUE TITLE
File Rename

### ISSUE THREAD

**Issue by rs-dhansen** [vgrem/phpSPO#114]
I found in your examples how to change folder names.

But, how to change file names?

When i try the code for folders with a file he said "malformed"

**Comment by rs-dhansen** [comment]
Additionally this not worked?

$fileObj = $ctx->getWeb()->getFileByServerRelativeUrl($currentSource);
$moveIt = $fileObj->moveTo($newSource, true);
$context = $fileObj->getContext();
$context->executeQuery();

The Moveto does nothing, same with copyto

**Comment by vgrem** [comment]
Greetings,

thank you for catching this issue, indeed it was a bug with parameters for `File.MoveTo` method, the following example demonstrates how to move/rename a file:

```
$sourceFile = $ctx->getWeb()->getFileByServerRelativeUrl("/sites/team/Shared Documents/sample.docx");
$ctx->load($sourceFile);
$targetFile = $sourceFile->moveTo("/sites/team/Shared Documents/sample_renamed.docx", MoveOperations::Overwrite);
    $ctx->executeQuery();

```
