### ISSUE TITLE
Error uploading file

### ISSUE THREAD

**Issue by lrobelo** [vgrem/phpSPO#117]
I'm receiving File not find error when upload a file. How can I solved it.? Thank you

**Comment by vgrem** [comment]
Greetings,

unfortunately without providing any details it's unclear why the error occurs.

Nowadays probably the simplest way to upload the file could be represented like this: 

```
$targetList = $ctx->getWeb()->getLists()->getByTitle($listTitle);
$fileContent = $file_get_contents($path)
$fileName = basename($path)
$uploadFile = $targetList->getRootFolder()->uploadFile($fileName,$fileContent);
$ctx->executeQuery();
```
