### ISSUE TITLE
First parameter must either be an object or the name of an existing class

### ISSUE THREAD

**Issue by KennHeiper** [vgrem/phpSPO#128]
Why does this error "First parameter must either be an object or the name of an existing class" pops up? 

@line 31 - https://github.com/vgrem/phpSPO/blob/master/examples/SharePoint/view_examples.php

**Comment by vgrem** [comment]
Greetings,

unfortunately i'm not able to reproduce it.

Trying to execute the same example i got those results: 

- either the list of view titles are printed 

- or the exception ` List '{list-title}' does not exist at site with URL '{web-url}'`  (this is expected exception in case if list is not available)

**Comment by vgrem** [comment]
My proposal to close this one due to inactivity
