### ISSUE TITLE
How to get total number of items

### ISSUE THREAD

**Issue by baltechies** [vgrem/phpSPO#137]
Hi,
Is there any way to get total number of items in list?
or can we get list items by batch like, 1-100 items, then 101-200 items, etc?

**Comment by vgrem** [comment]
Greetings,

[`List` resource](https://msdn.microsoft.com/en-us/library/office/dn531433.aspx#bk_ListProperties) exposes `ItemCount` property which:

> Gets a value that specifies the number of list items in the list.


**Example**

```
$authCtx = new AuthenticationContext($url);
$authCtx->acquireTokenForUser($userCreds['UserName'],$userCreds['Password']);
$ctx = new ClientContext($url,$authCtx);

$listTitle = 'Documents';
$list = $ctx->getWeb()->getLists()->getByTitle($listTitle);
$ctx->load($list);
$ctx->executeQuery();

$itemsCount = $list->getProperty('ItemCount');
```

Refer [this answer](https://sharepoint.stackexchange.com/a/139389/10610) for a more details and additional options
