### ISSUE TITLE
Memory leak caused by unused (debug?) code.

### ISSUE THREAD

**Issue by FritsvanCampen** [vgrem/phpSPO#138]
Hi,

I've discovered a severe memory leak in the library Runtime. This becomes very apparent if you're using ClientContext::openBinary() to download large files. The binary data is kept in memory forever with no way to clear it.

I've traced it back to this file/commit: https://github.com/vgrem/phpSPO/commit/d5af349fb41135abf7fc377eb5dc53c229155c10#diff-db16277e78d0bcf451ac0357e9f623db
This looks like debugging code to me.
I can't find any use of the getHistory() function so it should be safe to revert the file.

**Comment by vgrem** [comment]
Greetings!

Indeed there is no any dependency to `getHistory() function`  and not certain now why it was introduced

**Comment by vgrem** [comment]
In the [latest release ](https://github.com/vgrem/phpSPO/releases/tag/v2.4.0) all the unused variables  (including `history `array) have been deleted
