### ISSUE TITLE
Delete File

### ISSUE THREAD

**Issue by Jack89ita** [vgrem/phpSPO#139]
Hi!
I would like to know how to delete a file in sharepoint folder.
Searching through the the phpSPO directory i've found the method to delete a folder by its id, but not the one to delete a file.
Can you help me?
Thanks

**Comment by vgrem** [comment]
Greetings!

Indeed, `delete `operation was missing for a `File `resource.

Now the support for deleting file has been added, the following example demonstrates it: 


```
$ctx = new ClientContext($siteUrl,$authCtx);
$fileToDelete = $ctx->getWeb()->getFileByServerRelativeUrl("/Shared Documents/Archive 2018/Guide.docx");
$fileToDelete->deleteObject();
$ctx->executeQuery();

```
