### ISSUE TITLE
Documention or examples for how to use AuthenticationContext->acquireTokenForClientCredential

### ISSUE THREAD

**Issue by lhilton** [vgrem/phpSPO#143]
I would prefer to use a clientId/clientSecret for access my data. Is there an example somewhere of the acquireTokenForClientCredential being used correctly?

**Comment by ugalviar** [comment]
Our SharePoint admin followed the steps in [Accessing SharePoint Data using Postman (SharePoint REST API)](https://medium.com/@anoopt/accessing-sharepoint-data-using-postman-sharepoint-rest-api-76b70630bcbf).

And then we plugged in the values as such:

`$clientCredentials = new ClientCredential($clientId, $clientSecret);
$authCtx = new AuthenticationContext($authurl);
$authCtx->acquireTokenForClientCredential($resource, $clientCredentials);
$ctx = new ClientContext($url, $authCtx);`

**Comment by vgrem** [comment]
Greetings!

Please refer [wiki page](https://github.com/vgrem/phpSPO/wiki/How-to-connect-to-SharePoint-Online-and-and-SharePoint-2013-2016-2019-on-premises--with-app-principal) which explains how to create principal  and consent it to access resources.

Here is an example on how to use the principal's id and secret to request an access the resources:

```php

require_once __DIR__ . '/../vendor/autoload.php';

use Office365\Runtime\Auth\ClientCredential;
use Office365\SharePoint\ClientContext;


$credentials = new ClientCredential($clientId, $clientSecret);
$ctx = (new ClientContext($webUrl))->withCredentials($credentials);

$whoami = $ctx->getWeb()->getCurrentUser();
$ctx->load($whoami);
$ctx->executeQuery();
print $whoami->getLoginName();

```
