### ISSUE TITLE
Issue with file upload - E_RECOVERABLE_ERROR - File.php 248 - std class instead of a string

### ISSUE THREAD

**Issue by themullet** [vgrem/phpSPO#144]
Seeing 
<b>Recoverable fatal error</b>:  Object of class stdClass could not be converted to string in <b>/var/www/vhosts/edmsync/vendor/vgrem/php-spo/src/SharePoint/File.php</b> on line <b>248</b><br />

Looking at what's happening, it's got an class when it's in setProperty of File.php

Below is what it's getting caught on, think just need a check for string

object(stdClass)#492 (31) {
  ["Author"]=>
  NULL
  ["CheckedOutByUser"]=>
  NULL
  ["EffectiveInformationRightsManagementSettings"]=>
  NULL
  ["InformationRightsManagementSettings"]=>
  NULL
  ["ListItemAllFields"]=>
  NULL
  ["LockedByUser"]=>
  NULL
  ["ModifiedBy"]=>
  NULL
  ["Properties"]=>
  NULL
  ["VersionEvents"]=>
  NULL
  ["Versions"]=>
  NULL
  ["CheckInComment"]=>
  string(0) ""
  ["CheckOutType"]=>
  int(2)
  ["ContentTag"]=>
  string(46) "{04FD37C0-8B83-4E9A-B4F0-097F5226A598},531,887"
  ["CustomizedPageStatus"]=>
  int(0)
  ["ETag"]=>
  string(44) ""{04FD37C0-8B83-4E9A-B4F0-097F5226A598},531""
  ["Exists"]=>
  bool(true)
  ["IrmEnabled"]=>
  bool(false)
  ["Length"]=>
  string(8) "14321846"
  ["Level"]=>
  int(1)
  ["LinkingUri"]=>
  string(159) "https://*****.sharepoint.com/******/******.xlsx?d=w04fd37c08b834e9ab4f0097f5226a598"
  ["LinkingUrl"]=>
  string(151) "https://********.sharepoint.com/********/****.xlsx?d=w04fd37c08b834e9ab4f0097f5226a598"
  ["MajorVersion"]=>
  int(431)
  ["MinorVersion"]=>
  int(0)
  ["Name"]=>
  string(34) "*******.xlsx"
  ["ServerRelativeUrl"]=>
  string(84) "/********/*******.xlsx"
  ["TimeCreated"]=>
  string(20) "2017-07-11T14:02:26Z"
  ["TimeLastModified"]=>
  string(20) "2019-04-23T05:31:39Z"
  ["Title"]=>
  string(0) ""
  ["UIVersion"]=>
  int(220672)
  ["UIVersionLabel"]=>
  string(5) "431.0"
  ["UniqueId"]=>
  string(36) "04fd37c0-8b83-4e9a-b4f0-097f5226a598"
}

This is from file upload using uploadFileIntoFolder found in - 
https://github.com/vgrem/phpSPO/blob/master/examples/SharePoint/file_examples.php 

---- 

I've got the error caught using a set_error_handler

**Comment by vgrem** [comment]
Greetings!
Thanks for reporting the issue.

JSON mapper  into model classes has been refactored lately and it appears this kind of error should no longer occur.
Vadim
