### ISSUE TITLE
Only variables should be passed by reference to the end() function in ClientObject.php line 57

### ISSUE THREAD

**Issue by dramentol** [vgrem/phpSPO#15]
I proposse this change on ClientObject.php line 57:

`-            $path = strtolower(end(explode("\\",get_class($this))));`

`+            $explode = explode("\\",get_class($this));`
`+            $path = strtolower(end($explode));`

**Comment by rbertram** [comment]
Your proposal solved the issue for me as well.
+1

**Comment by rbertram** [comment]
Any thoughts regarding this one @vgrem? I just updated to the latest version and this error struck me once again.

**Comment by vgrem** [comment]
Greetings,
The issue has been resolved according to your proposal.
Thanks!
