### ISSUE TITLE
How would one go about copying a directory?

### ISSUE THREAD

**Issue by Jiggles98** [vgrem/phpSPO#150]
I am currently working on a script that copies a folder to another directory, then renames said folder. From the examples I can see how you would go about renaming and even copying files from a directory given the copyTo method. However, it appears the method does not exist in regards to folders. Is there a way someone could copy a directory/folder?

**Comment by vgrem** [comment]
To anyone who will come across this question, nowadays _copy folder operation_ is supported on library level:

```
$sourceFolder =  $client->getWeb()->getFolderByServerRelativeUrl($url);
$targetFolder = $sourceFolder->copyTo($targetFolderUrl,true);
$client->executeQuery();
```

**Comment by RajuSysalgo** [comment]
$sourceFolder =  $client->getWeb()->getFolderByServerRelativeUrl($url);
$targetFolder = $sourceFolder->copyTo($targetFolderUrl,true);
$client->executeQuery();

this code only works for files not for folder
