### ISSUE TITLE
Unable to Rename Folder using renameFolder example.

### ISSUE THREAD

**Issue by rjohnson-vrx** [vgrem/phpSPO#151]
I am fairly new to using sharepoint and I am trying to rename a folder using
the renameFolder.php example.  I successfully authenticate and when running this example with my changes, I get a message back stating ERROR: malformed.

I display the request variable to see what it's contents are and don't see any data that I would expect.  Can you please suggest a possible remedy?  Could there be any reason that there is no data associated with a folder on sharepoint.  I was able to successfully create folders and subfolders with php-spo.  This is giving me some trouble.

object(Office365\PHP\Client\Runtime\Utilities\RequestOptions)#6 (12) {
  ["Url"]=>
  string(129) "https://xxxxxxxx.sharepoint.com/_api/web/getFolderByServerRelativeUrl('/sites/Archive/Shared Documents/AA_test')/ListItemAllFields"
  ["Method"]=>
  string(3) "GET"
  ["Headers"]=>
  array(0) {
  }
  ["Data"]=>
  NULL
  ["IncludeHeaders"]=>
  bool(false)
  ["IncludeBody"]=>
  bool(true)
  ["AuthType"]=>
  NULL
  ["UserCredentials"]=>
  NULL
  ["Verbose"]=>
  bool(false)
  ["SSLVersion"]=>
  NULL
  ["StreamHandle"]=>
  NULL
  ["Proxy"]=>
  NULL
}

Please see code snippet 

<?php
require_once 'sharepoint1/bootstrap.php';

use Office365\PHP\Client\Runtime\Auth\AuthenticationContext;
use Office365\PHP\Client\Runtime\Utilities\RequestOptions;
use Office365\PHP\Client\SharePoint\ClientContext;

try {
	$authCtx = new AuthenticationContext($Settings['Url']);
	$authCtx->acquireTokenForUser($Settings['UserName'],$Settings['Password']);
$Settings['Url']="https://verrex1.sharepoint.com";

//print "<pre>";
//var_dump(${authCtx});
//print "</pre>";
//exit;
    $folderUrl = "/sites/Archive/Shared Documents/AA_test";
    $folderNewName = "Archive2014";
    renameFolder($Settings['Url'],$authCtx,$folderUrl,$folderNewName);
    
}
catch (Exception $e) {
	echo 'Error: ',  $e->getMessage(), "\n";
}
function renameFolder($webUrl, $authCtx, $folderUrl,$folderNewName)
{
    $url = $webUrl . "/_api/web/getFolderByServerRelativeUrl('{$folderUrl}')/ListItemAllFields";
    $request = new RequestOptions($url);
print "<pre>";
var_dump(${request});
print "</pre>";
exit;
    $ctx = new ClientContext($url,$authCtx);
//print "<pre>";
//var_dump(${authCtx});
//print "</pre>";
//exit;
    $resp = $ctx->executeQueryDirect($request);
    $data = json_decode($resp);
    $itemPayload = array( 
        '__metadata' => array ('type' => $data->d->__metadata->type),
        'Title' => $folderNewName,
        'FileLeafRef' => $folderNewName
        );
    $itemUrl = $data->d->__metadata->uri;
    $request = new RequestOptions($itemUrl);
    $request->addCustomHeader("X-HTTP-Method", "MERGE");
    $request->addCustomHeader("If-Match", "*");
    $request->Data = $itemPayload;
    $ctx->executeQueryDirect($request);
}

?>

**Comment by vgrem** [comment]
Greetings!

Renaming folder operation is supported via `rename` method of [`Folder `class](https://github.com/vgrem/phpSPO/blob/master/src/SharePoint/Folder.php)

**Example**

```
$folder = $client->getWeb()->getFolderByServerRelativeUrl("{server-relative-path-to-folder}"); 
$folder->rename($newFolderName);
$client->executeQuery();
```
