### ISSUE TITLE
Download public sharepoint file

### ISSUE THREAD

**Issue by merlinthemagic** [vgrem/phpSPO#153]
I have been sent a URL to a file that resides on our cloud hosted share point server. The file is a publicly accessible spreadsheet and can be accessed without credentials. I need to download that file for processing, but I cannot figure out how to instantiate a Client Context without credentials.
[Same Question Here on SO](https://sharepoint.stackexchange.com/questions/264184/download-a-file-from-sharepoint-online-using-php)

The below results in a "Unknown authentication provider" Exception.
```
$fileUrl	= "https://mycompany.sharepoint.com/folders/someGUIDlikeSTRING?somevar=someval&anothervar=etc";
$url		= "https://mycompany.sharepoint.com";
$authCtx	= new \Office365\PHP\Client\Runtime\Auth\AuthenticationContext($fileUrl);
$ctx		= new \Office365\PHP\Client\SharePoint\ClientContext($url, $authCtx);
$fileObj	= new \Office365\PHP\Client\SharePoint\File($ctx);
$data		= $fileObj->openBinary($ctx, $fileUrl);
```

I did get it to work with the hackish solution below, but i would rather handle it in phpSPO:
```
$fileUrl    = "https://mycompany.sharepoint.com/folders/someGUIDlikeSTRING?download=1";
$filePath   = "/tmp/saveHere.file";
$strCmd     = "wget -O  " . $filePath . " " . $fileUrl;
shell_exec($strCmd);
```
Using Curl I kept receiving a 403, while wget worked fine. Its a hackish shell call, obviously curl would be a far better solution, but it works.

**Comment by vgrem** [comment]
Greetings!

I propose to close this issue since it has been already resolved (refer to answers for the [provided question in SO](https://sharepoint.stackexchange.com/questions/264184/download-a-file-from-sharepoint-online-using-php)).
