### ISSUE TITLE
Get custom attributes (columns) from file in library

### ISSUE THREAD

**Issue by mix1981** [vgrem/phpSPO#156]
Hi, 
I'm trying to retrieve custom attributes (columns) from file I've previously uploaded to Sharepoint Library. I can set any custom attribute using
```
....
$propname='CustomClassification';
$propval='Very Important';
$uploadFile->getListItemAllFields()->setProperty($propname,$propval); 
....
```
And it is working perfect - file in library has proper value for this custom column (attribute). 

But I have no idea how to read this property while listing files! I'm trying to use sth like this: 
```
....
$propname='CustomClassification';
$files = $ctx->getWeb()->getFolderByServerRelativeUrl($targetFolderUrl)->getFiles();
$ctx->load($files);
$ctx->executeQuery();
foreach ($files->getData() as $file) {
   print "File name: '{$file->getProperty("ServerRelativeUrl")}.'\r\n";
   print "File classification: '{$file->getProperty($propname)}.'\r\n";
};
....
```
The $file has a lot of default attributes (f.e. Author, ModifiedBy, TimeCreated...) but none of mu custom colums. Is it possible to retrieve that values?

**Comment by vgrem** [comment]
Greetings,

surely custom properties are retrievable, via `ListItem` entity _associated_ with a `File`.
Here is the list of changes:

fist of all, custom file properties need to be explicitly requested, for example via `$expand` query options:

`$files = $ctx->getWeb()->getFolderByServerRelativeUrl($targetFolderUrl)->getFiles()->expand("ListItemAllFields");
`

now custom file properties could be accessed like this: 

```
$properties = $file->getListItemAllFields();
print "File classification: '{$properties->{$propname}}.'\r\n";
```

 

 



**Modified example**

```
$files = $ctx->getWeb()->getFolderByServerRelativeUrl($targetFolderUrl)->getFiles()->expand("ListItemAllFields");
    $ctx->load($files);
    $ctx->executeQuery();
    /* @var $file File */
    foreach ($files->getData() as $file) {
        print "File name: '{$file->getProperty("ServerRelativeUrl")}.'\r\n";
        $properties = $file->getListItemAllFields();
        print "File classification: '{$properties->{$propname}}.'\r\n";
    };

```

**Comment by mix1981** [comment]
Wow, thank you very much. This is exactly what I was looking for.
Thank you for the whole phpSPO - this is wonderful library.

czw., 5 wrz 2019 o 10:22 Vadim Gremyachev <notifications@github.com>
napisał(a):

**Comment by mix1981** [comment]
Sorry for bothering, but can i have one more question? I'm trying to update
a multiple lookup column, and get error:

if (is_array($SelectedIDS))
    $app->setProperty('SomeColumnId', $SelectedIDS);
$app->update();
$ctx->executeQuery();

but i get:
Uncaught Exception: A node of type 'StartArray' was read from the JSON
reader when trying to read a value of a property; however, a
'PrimitiveValue' or 'StartObject' node was expected. in .....

When i display this value, it is an array... should I update this field
other way?
Thank you in advance,
Michał

czw., 5 wrz 2019 o 10:22 Vadim Gremyachev <notifications@github.com>
napisał(a):

**Comment by vgrem** [comment]
Good question and i confirm it is expected error since field value is not getting properly mapped. 
Although i must to agree it is not very convenient  since the library should be able to handle  properly map field values.

At the moment field value needs to be provided in the following format:

    $lookupValue = array(
        'results' => $SelectedIDS
    );
    $listItem->setProperty("SomeColumnId",$lookupValue);
 



**Sample**

Demonstrates how to update _multi-valued_ lookup field

> Note: while updating field value, its name needs to be provided in format: `<FieldName>Id`, for example  if field named `Categories`  then it should be specified as `CategoriesId`

Field value format:  

  ```
 "FieldName" : {
         "results" : [<LookupVal1>,<LookupVal2>,...]
   }
```


    $listItem = $ctx->getWeb()->getLists()->getByTitle("Documents")->getItemById(1);

    $lookupValue = array(
        'results' => [1,2]
    );
    $listItem->setProperty("CategoriesId",$lookupValue);
    $listItem->update();
    $ctx->executeQuery();



With regard,
Vadim

**Comment by mix1981** [comment]
Than You, it is working exactly as you said. I think it would be very
useful if such little more complicated examples also were in exemple files
in your github exapmle section- anyway, thank you once again :)

Michal

czw., 5 wrz 2019 o 16:30 Vadim Gremyachev <notifications@github.com>
napisał(a):

**Comment by gabrielMoran23** [comment]
Hello and do you know how to read the property and get all elements with the same pattern ? Some thing like sql where

**Comment by aman90attari** [comment]
Hi, Can someone suggest how we can get value of other column rather than Title in sharepoint list 

$list = $ctx->getWeb()->getLists()->getByTitle("Add Shift");
	$items = $list->getItems();
	//$this->pr($items);
	$ctx->load($items);
	$ctx->executeQuery();
	
	// print $items->getCount() . PHP_EOL;
	foreach ($items as $index => $item){
		print($index . ":" . $item->getProperty('Title') . PHP_EOL);
		echo "-----------------------------------------------------------";
		print($index . ":" . $item->getProperty('Start Date') . PHP_EOL);
	}
