### ISSUE TITLE
Adding users to sharepoint groups

### ISSUE THREAD

**Issue by matrixcoder84** [vgrem/phpSPO#157]
Unable to add users to sharepoint groups. Could someone help me?

**Comment by vgrem** [comment]
Greetings!

method for adding user was missing but has been introduced in the _latest_ commit.

**Example** 

```
$targetGroupName = "--group--name-goes--here--";
$loginName = "i:0#.f|membership|jdoe@contoso.onmicrosoft.com";

$client = new ClientContext($url,$authCtx);
$targetGroup = $client->getWeb()->getSiteGroups()->getByName($targetGroupName);
$user = $targetGroup->getUsers()->addUser(self::$testLoginName);
$client->executeQuery();

```

**Comment by matrixcoder84** [comment]
Thank you very much Vadim!

Luca Dall'Ara

Il Lun 28 Ott 2019, 20:02 Vadim Gremyachev <notifications@github.com> ha
scritto:
