### ISSUE TITLE
Handle OData Query operators ($expand, $filter) on getitems

### ISSUE THREAD

**Issue by Danny-Engelman** [vgrem/phpSPO#16]
[Great project, saves me from migrating my sites to Azure]

Note that the batch methods are capped at returning 100 items.

Are you planning on a syntax?

And for now, how can I add them myself; this gives me an error

```
public function getItems()
    {
        $filter='$top=10';
        return new ListItemCollection($this->getContext(),$this->getResourcePath(),"items".$filter);
    }
```

**Comment by rbertram** [comment]
I've created the following temporary method. Put it inside src/List.php.

```
public function get($object, array $parameters = [])
{
    $resourcePath = $this->getResourcePath() . '/' . $object;

    if ($parameters) {
        $resourcePath = $resourcePath . '?' . http_build_query($parameters);
    }

    $items = new ListItemCollection($this->getContext(), $resourcePath);

    return $items;
}
```
And I use it like this:
```
$items = $list->get('items', ['$expand' => 'AttachmentFiles']);
```

**Comment by Danny-Engelman** [comment]
I am sorry for my rusty PHP skills.. it has been a while...

                $items = $list->get('items', ['$top' => '10']);

results in

    Error: The $top expression "10/listitemcollection" is not valid.

So I tried

            $resourcePath = $resourcePath . '?$top=10';

without luck

But my 27 year old (not my age) URI infested brain came up with:

            $resourcePath = $resourcePath . '?$top=10&';

which does work

So I presume ``ListItemCollection`` has a bug

**Comment by rbertram** [comment]
It looks like Vgrem have made some significant refactoring. I've updated my previous example.

If you have a look at https://github.com/vgrem/phpSPO/blob/master/src/List.php#L62 you will see that there now is a third parameter. This is where my example failed. I noticed it after I updated to the latest version myself. Update the code and give it another go.

**Comment by vgrem** [comment]
Greetings Danny & Robin!

Indeed support for [query options](https://msdn.microsoft.com/en-us/library/gg309461(v=crm.7).aspx) was not available before.

**Currently** the SDK supports the query options listed in [OData system query options using the OData endpoint](https://msdn.microsoft.com/en-us/library/gg309461(v=crm.7).aspx) MSDN page.

 


# Examples


Example 1. How to retrieve top 5 list items

```
$items = $list->getItems()->top(5);  //apply top query option
$ctx->load($items);
$ctx->executeQuery();
foreach( $items->getData() as $item ) {
    print "Task: '{$item->Title}'\r\n";
}
```


Example 2. How to select only a specific set of fields(properties) for list items

```
$items = $list->getItems()->select('Title,Id');  //apply select query option
$ctx->load($items);
$ctx->executeQuery();
foreach( $items->getData() as $item ) {
    print "Task: {$item->Id}, {$item->Title}\r\n";
}

```

Example 3. How to find list item with ID property set to 1 

```
$items = $list->getItems()->filter('ID eq 1');  //apply filter query option
$ctx->load($items);
$ctx->executeQuery();
foreach( $items->getData() as $item ) {
	print "Task: '{$item->Title}'\r\n";
}

```

Example 4. How to select a projected field values

> Note: in the provided example the field is of multi-user field type

 

```
$items = $list->getItems()->select('Title,AssignedTo/Id,AssignedTo/Title')->expand('AssignedTo');  //apply select & expand query options
$ctx->load($items);
$ctx->executeQuery();
foreach( $items->getData() as $item ) {
	print "Task: '{$item->Title}, {$item->AssignedTo->results[0]->Title}'\r\n";
}

``` 

Please follow [listitem_examples.php](https://github.com/vgrem/phpSPO/blob/master/examples/listitem_examples.php) for a more examples.
