### ISSUE TITLE
Sharepoint: Grant user/group permissions to folder

### ISSUE THREAD

**Issue by matrixcoder84** [vgrem/phpSPO#160]
Dear,

I would kindly ask you if you can help me to grant user/group sharepoint permissions to list folders. This is the c# implementation:

`var roletypes = clientContext.Web.RoleDefinitions.GetByType(RoleType.Contributor);
clientContext.ExecuteQuery();
listItemObject.BreakRoleInheritance(true, false);
RoleDefinitionBindingCollection collRoleDefinitionBinding = new RoleDefinitionBindingCollection(clientContext);
collRoleDefinitionBinding.Add(roletypes);
listItemObject.RoleAssignments.Add(grp, collRoleDefinitionBinding);
listItemObject.Update();
clientContext.ExecuteQuery();`

I don't find the php _RoleDefinitionBindingCollection_ implementation. Do you have any suggestions of what I can do? 

It would be an urgent need on business,  if you could help or even just give me a hint, it would be greatly appreciated.

Thanks in advance

**Comment by vgrem** [comment]
Greetings,

indeed, role assignment is not completely supported (`v2.2.4`) but you could grab the _latest_ master branch:

`composer require vgrem/php-spo:dev-master -n --no-progress  `

which adds support for `addRoleAssignment` method.

**Example**

Demonstrates how to assign permissions for the user on the file
    
    $fileUrl = "/Shared Documents/Book1.xlsx";
    $file = $ctx->getWeb()->getFileByServerRelativeUrl($fileUrl);
    $listItem = $file->getListItemAllFields();
    $listItem->breakRoleInheritance(false);
    $ctx->executeQuery();

    //get role definition
    $roleDefs = $ctx->getWeb()->getRoleDefinitions();
    $ctx->load($roleDefs);
    $ctx->executeQuery();


    //get site users
    $siteUsers = $ctx->getWeb()->getSiteUsers();
    $ctx->load($siteUsers);
    $ctx->executeQuery();


    //Add the new role assignment for the user on the file
    $targetRole = $roleDefs->findFirst("Name","Edit");
    $targetUser = $siteUsers->findFirst("Title","Marta Doe");
    $listItem->getRoleAssignments()->addRoleAssignment($targetUser->getProperty("Id"),$targetRole->getProperty("Id"));
    $ctx->executeQuery();


**Result**

![image](https://user-images.githubusercontent.com/1596072/65179808-33abe980-da64-11e9-8e93-ed7c76cc844a.png)

**Comment by matrixcoder84** [comment]
Dear Vadim,

first of all thanks for your prompt reply.

I made a composer update but the code hasn't been updated yet and don't
find  addRoleAssignment  method
The same when I run *composer remove* and then composer require
vgrem/php-spo:dev-master -n --no-progress  as you indicate, the code isn't
updated.

Instead if  I manually download
https://github.com/vgrem/phpSPO/archive/master.zip, the code is updated but
it doesn't work because replacing the source file I get method unexisting.


Could you help me?


Il giorno mer 18 set 2019 alle ore 22:58 Vadim Gremyachev <
notifications@github.com> ha scritto:

**Comment by matrixcoder84** [comment]
Thank you. Now it works regularly.

Kind regards

Il gio 19 set 2019, 20:50 Vadim Gremyachev <notifications@github.com> ha
scritto:
