### ISSUE TITLE
Cannot upgrade through Packagist

### ISSUE THREAD

**Issue by Deuchnord** [vgrem/phpSPO#162]
Not sure if you can do something on this, but the [package on Packagist](https://packagist.org/packages/vgrem/php-spo) has not been updated with the recent `2.3.0` tag, so we cannot upgrade the library on our side.
Are you able to do something on this, or is it on Packagist's side?

**Comment by Deuchnord** [comment]
Packagist just got updated, closing this issue :)

**Comment by vgrem** [comment]
Just noticed it as well. 

Not sure, why package was not updated instantly, just reconfigured webhook configuration.
