### ISSUE TITLE
[Question] How to get a list of files/directories in a certain directory

### ISSUE THREAD

**Issue by mbootsman** [vgrem/phpSPO#166]
Hi, thanks for this great library.
I successfully managed to connect to a sharepoint environment.
Now I need to get the files/directories in a certain parent directory.

What would be the way to do this?

**Comment by mbootsman** [comment]
After testing and going through the examples, I've got it working.
Code I have tested it with:
```
try {
		$ctx  = connectWithAppOnlyToken( SERVER_URL, CLIENT_ID, CLIENT_KEY );
		$site = $ctx->getSite();
		$ctx->load( $site ); //load site settings
		$ctx->executeQuery();
		echo '<p> 🎉 Connected! The site url is: ' . $site->getProperty( "Url" ) . '</p>';

		$files = $ctx->getWeb()->getFolderByServerRelativeUrl($targetFolderUrl)->getFolders();
		$ctx->load($files);
		$ctx->executeQuery();

		//print files info
		/* @var $file File */

		foreach ($files->getData() as $file) {
			print "Directory name: '{$file->getProperty("ServerRelativeUrl")}'<br />";
		}
	} catch ( Exception $e ) {
		echo 'Authentication failed: ', $e->getMessage(), "\n";
	}
```

**Comment by gabrielMoran23** [comment]
hey mbootsman, can you helpe me?, i did this but my response only shows me the folder name, not my files name, what im oing worng,
my site is cv_files, and my library candidates_cv those are  public, what i need to do?

**Comment by mbootsman** [comment]
> hey mbootsman, can you helpe me?, i did this but my response only shows me the folder name, not my files name, what im oing worng,
> my site is cv_files, and my library candidates_cv those are public, what i need to do?
When using `$ctx->getWeb()->getFolderByServerRelativeUrl( $url )->getFolders();` you only get folders in the response.
Use `$ctx->getWeb()->getFolderByServerRelativeUrl( $url )->getFiles();` to get the files.

**Comment by gabrielMoran23** [comment]
To much Thanks, it worked !
