### ISSUE TITLE
X509 Certificate

### ISSUE THREAD

**Issue by coreation** [vgrem/phpSPO#168]
Hi there,

first of all, thank you very much for maintaining this code base, I can tell there's a lot of effort going into this!

My question is with regards to authentication, I have a client certificate that I need to use to authenticate myself, but I'm not sure how this would work with this library. Is that something that needs to be implemented and configured when making a cURL request for example?

**Comment by vgrem** [comment]
Hi, 

nowadays the library has a built in support for app-only access via X.509 certificate, here is an example:

```php
$siteUrl = "https://contoso.sharepoint.com";  //site or web absolute url 
$tenant = "contoso.onmicrosoft.com"; //tenant id or name
$thumbprint = "--thumbprint goes here--";
$clientId = "--client app id goes here--";
$privateKeyPath = "-- path to private.key file--"
$privateKey = file_get_contents($privateKeyPath);

$ctx = (new ClientContext($siteUrl))->withClientCertificate(
    $tenant, $clientId, $privateKey, $thumbprint);

$whoami = $ctx->getWeb()->getCurrentUser()->get()->executeQuery();
print $whoami->getLoginName();  

```



Refer [wiki page](https://github.com/vgrem/phpSPO/wiki/Granting-access-via-Azure-AD-App%E2%80%90Only-with-Certificate) for a more details

#326 related
