### ISSUE TITLE
ErrorException in ClientRequest.php line 45: Undefined index: headers

### ISSUE THREAD

**Issue by rbertram** [vgrem/phpSPO#17]
```
ErrorException in ClientRequest.php line 45:
Undefined index: headers
```
After running the following code.
```
\SharePoint\PHP\Client\File::openBinary($ctx, $item->ServerRelativeUrl);
```
The method `openBinary` misses the option headers (`$options["headers"]`) which seems to be required by `executeQueryDirect`. I solved it temporary by doing the following.
```
public function executeQueryDirect($options)
{
    if (!isset($options["headers"])) {
        $options["headers"] = [];
    }
    ...
```

**Comment by MartijnDevNull** [comment]
Same problem here, when I try go use get with `executeQueryDirect` constantly get this error
