### ISSUE TITLE
Sharepoint File Grant Public access and obtain link

### ISSUE THREAD

**Issue by arpmota** [vgrem/phpSPO#173]
Hi
I would like to know if is possible to grant public access to a file in sharepoint 
and obtain the shared link?

Thank you vey much

André

**Comment by arpmota** [comment]
Does anyone ever been abble to obtain the link and not just get the file?

**Comment by vgrem** [comment]
Greetings!

## Regarding obtaining a file link:

The following example demonstrates how to retrieve file absolute url:

```
$file = $ctx->getWeb()->getFileByServerRelativeUrl("/Shared%20Documents/Sample.xlsx");
$ctx->load($file);
$ctx->executeQuery();
$fileUrl = $file->getLinkingUrl();
```




## Regarding _granting public access_, the following methods available via SharePoint API:


- [`Web.CreateAnonymousLink` method](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/mt143091(v%3Doffice.15)) - Create an anonymous link which can be used to access a document without needing to authenticate.

- [`Web.CreateAnonymousLinkWithExpiration` method](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/mt143090(v=office.15)) - Create an anonymous link which can be used to access a document without needing to authenticate. 


And they are supported by library, here is an example for `Web.CreateAnonymousLink` method:

> Note: due to the bug with static methods,  please make sure to grab the latest version of library from GitHub:
> 
> ```
> {
>     "require": {
>         "vgrem/php-spo": "dev-master"
>     }
> }
> ``` 
> 

**Example**


```
$fileUrl = "https://contoso.sharepoint.com/Shared%20Documents/Sample.xlsx";
$result = Web::createAnonymousLink($ctx,$fileUrl,false);
$ctx->executeQuery();
$fileSharedLink = $result->getValue();

```
