### ISSUE TITLE
Backwards compatibility - break

### ISSUE THREAD

**Issue by frank-miller9** [vgrem/phpSPO#175]
Hello,

I really like the library here, thank you very much.

Today I made an update via composer and my project broke.

It seems this project does not follow any semantic version rules, like the one proposed by composer:
https://getcomposer.org/doc/articles/versions.md

```"vgrem/php-spo": "^2.2"```

did break scripts, because methods are removed or renamed within the 2.x line. So is there any official statement regarding backwards compatibility? It would be great if you could stick to the "common sense".

Thank you again, the library is fantastic, if you get the version right :)

**Comment by vgrem** [comment]
Greetings!

sorry to hear it broke the scripts.  Promises do not modify API except Model  (which gets updated only from metadata) and  to keep an eye to maintain backwards compatibility between releases.

Meanwhile you might be interested to upgrade to the [latest (`2.4.1`) release](https://github.com/vgrem/phpSPO/releases/tag/v2.4.1)  which brings the following improvements among others:

- built-in support to retrieve large collections (or paged data) via lazy loading approach

- support for upload "large" file (chunked upload)

[More details ](https://github.com/vgrem/phpSPO/releases/tag/v2.4.1
)
