### ISSUE TITLE
CamlQuery possible?

### ISSUE THREAD

**Issue by tuechler** [vgrem/phpSPO#180]
is it possible to use caml queries for Sharepoint lists?
if a CamlQuery Object is passed to the getItems() method I always get an error:
Fatal error</b>:  Uncaught Error: Call to a member function getSegment() on null in /var/www/html/pipe/pipe2020/vendor/vgrem/php-spo/src/Runtime/ClientObject.php:237
Stack trace:
#0 /var/www/html/pipe/pipe2020/vendor/vgrem/php-spo/src/Runtime/ClientObject.php(289): Office365\Runtime\ClientObject-&gt;setProperty()
#1 /var/www/html/pipe/pipe2020/vendor/vgrem/php-spo/src/Runtime/ClientObjectCollection.php(246): Office365\Runtime\ClientObject-&gt;mapJson()
#2 /var/www/html/pipe/pipe2020/vendor/vgrem/php-spo/src/Runtime/OData/ODataRequest.php(170): Office365\Runtime\ClientObjectCollection-&gt;mapJson()
#3 /var/www/html/pipe/pipe2020/vendor/vgrem/php-spo/src/Runtime/OData/ODataRequest.php(157): Office365\Runtime\OData\ODataRequest-&gt;mapJson()
#4 /var/www/html/pipe/pipe2020/vendor/vgrem/php-spo/src/Runtime/ClientRequest.php(124): Office365\Runtime\OData\ODataRequest-&gt;processResponse()
#5 /var/www/html/pipe/pipe2020/vendor/vgrem/php-spo/src/Runtime/ClientRuntimeContext.php(126): Office365\Runtime\ClientRequest-&gt;executeQuery()
#6 /var/www/html/p in <b>/var/www/html/pipe/pipe2020/vendor/vgrem/php-spo/src/Runtime/ClientObject.php</b> on line <b>237</b>

here is my code:

```
<?php

require_once '../../vendor/autoload.php';
require_once 'settings_tal.php';

use Office365\Runtime\Auth\AuthenticationContext;
use Office365\SharePoint\ClientContext;
use Office365\SharePoint\CamlQuery;

    $authCtx = new AuthenticationContext($settings["spsite"]);
    $authCtx->acquireTokenForUser($settings["user"], $settings["pwd"]); //authenticate
    $ctx = new ClientContext($settings["spsite"], $authCtx); //initialize REST client
    $web = $ctx->getWeb();
    $list = $web->getLists()->getByTitle("Personalliste");

    $qry = new CamlQuery();
    $qry->ViewXml = '<View><Query><Where><Eq><FieldRef Name="Abteilung" LookupId="True" /><Value Type="Text">PC2-Technik</Value></Eq></Where></Query></View>';
    
    $items = $list->getItems($qry); // ERROR
    // $items = $list->getItems();  //no error when argument is missing

    $ctx->load($items);
    $ctx->executeQuery();

    $li=array();
    foreach ($items->getData() as $l) {
            $v = array( $l->getId(), 
                        $l->__get("Title"), 
                        $l->__get("Abteilung"), 
                        $l->__get("Lieferort"), 
                        $l->__get("Author"),
                    );      
            $li[] = $v;
        }

    echo json_encode($li);
   
    ?>
```

**Comment by vgrem** [comment]
Greetings!

Thanks for catching this bug! It's been resolved the latest commit.

Btw, since `$items` collection is traversable, `getData()` method could be omitted, here is an example:

```
$list = $ctx->getWeb()->getLists()->getByTitle("Tasks");
$qry = new CamlQuery();
$qry->ViewXml = '<View><Query><Where><Eq><FieldRef Name="Editor" LookupId="TRUE" /><Value Type="Integer"><UserID /></Value></Eq></Where></Query></View>';
$items = $list->getItems($qry);
$ctx->executeQuery();

foreach ($items as $index => $item){
    print($index . ":" . $item->getProperty('Title') . PHP_EOL);
}

```
