### ISSUE TITLE
LICENSE.md says MIT, composer.json says LGPL-3.0+

### ISSUE THREAD

**Issue by oo453** [vgrem/phpSPO#181]
Hi,
I'm not sure which license is the correct one.
LICENSE.md contains MIT-License, whereas composer.json states LGPL-3.0+-License.

Please change either LICENSE.md or composer.json

Thanks in advance
Kind regards

**Comment by vgrem** [comment]
Greetings,

thanks for catching it, `composer.json` license has been updated to  `MIT`

**Comment by oo453** [comment]
Thanks!
Can you change it in the README.md too?

**Comment by vgrem** [comment]
In Readme.md licence badge is generated via https://packagist.org/, i guess the changes will get reflected as soon the new version (`2.4.2`) is published, will let you know.
