### ISSUE TITLE
Create a folder link in SharePoint

### ISSUE THREAD

**Issue by samueldk12** [vgrem/phpSPO#183]
Hey so, I need create a folder link, of my new folder, for acess in webpage.
`
         $settings = include(__DIR__ . '\..\vendor\vgrem\php-spo\Settings.php');
           
                    $authCtx = new AuthenticationContext($settings['Url']);
                  
                    $authCtx->acquireTokenForUser($settings['UserName'],$settings['Password']);
                    
                    $ctx = new ClientContext($settings['Url'],$authCtx);
          
                    $path = cliente::getPathClienteSharePoint($cliente);
                    
                    $parentFolder = $ctx->getWeb()->getFolderByServerRelativeUrl("/sites/Backup/Documentos%20Compartilhados/Comercial/Propostas/".$path);
                    $folder = $parentFolder->getFolders()->add($proposta->nomeproposta);
                    $url = $settings['Url']."sites/Backup/Documentos%20Compartilhados/Comercial/Propostas/".$path.'/'.$proposta->nomeproposta;
                    $result = Web::createAnonymousLink($ctx,$url,true);
                    $ctx->executeQuery();
                    $url = $result->getValue();
                    $parentFolder = $ctx->getWeb()->getFolderByServerRelativeUrl("/sites/Backup/Documentos%20Compartilhados/Comercial/Propostas/".$path.'/'.$proposta->nomeproposta);
                    $folder = $parentFolder->getFolders()->add('Recibos do Cliente');
                    $ctx->executeQuery();
                    $folder = $parentFolder->getFolders()->add('Propostas Técnica e Custos');
                    $ctx->executeQuery();
                    $folder = $parentFolder->getFolders()->add('Proposta Comercial');
                    $ctx->executeQuery();
                     
                   
                    echo $url;
`

I want to return the link only for the first folder created

**Comment by SAA-Educacao** [comment]
I also have this problem, and I'm not getting it in any way
