### ISSUE TITLE
Unable to access newly added fields in sharepoint 2016

### ISSUE THREAD

**Issue by aman90attari** [vgrem/phpSPO#186]
Newly added fields are not returning through 

                $authCtx = new NetworkCredentialContext($username, $password);
		$authCtx->AuthType = CURLAUTH_NTLM;
		$ctx = new ClientContext($url,$authCtx);

		$list = $ctx->getWeb()->getLists()->getByTitle("Add Shift");
		$items = $list->getItems();
		//$this->pr($items);
		$ctx->load($items);
		$ctx->executeQuery();
		
		// print $items->getCount() . PHP_EOL;
		foreach ($items as $index => $item){
			print($index . ":" . $item->getProperty('Title') . PHP_EOL);
			echo "-----------------------------------------------------------";
			print($index . ":" . $item->getProperty('Start Date') . PHP_EOL);
		}

Real Output

Shift name A
Shift name B

Expected Output 

Shift name A
2020-06-15 12:13:00
Shift name B
2020-06-18 12:13:00

I am unable to figure out why $ctx object not returning this column in  sharepoint list which name is add shift 
 Object out put is too long if some one need to know to figure out the problem please let me know i will provide it.
Please check if some body can help on this

**Comment by vgrem** [comment]
`ListItem.getProperty` method expects  field _internal name_ , in your example most likely `Start Date` corresponds to field _display name_.

To find out field internal name, go to List settings -> under `Columns` locate the field and on go to field settings page, field internal name could be determined from url as depicted below

![image](https://user-images.githubusercontent.com/1596072/84653467-226e0b80-af16-11ea-9d7f-95efe9b4d063.png)

**Comment by aman90attari** [comment]
Thank you so much @vgrem, It worked
