### ISSUE TITLE
New version - Information

### ISSUE THREAD

**Issue by ChangingTerry** [vgrem/phpSPO#196]
Hi,

Firstly thanks for such a wonderful project (few more docs would be nice). It looks like you are gearing up for a new major version? I'm not going to bug you for timescales, but I was wondering if thier is anywhere public where I can track progress / design changes etc? 

I'm currently developing a new project using this libary and would like to keep up-to-date on upcoming changes, make contrbutions to docs etc?

Thank you

**Comment by vgrem** [comment]
Greetings!

Thank you for your interest!

Indeed, the next major version `2.5.0 `is about the corner (expected release date by end of this month) which will finally bring a long awaited support for [batch requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis) (which from a performance perspective will be huge win in some cases). Along the way will be released a few minor versions with improvements (e.g. support for [Fluent interface](https://en.wikipedia.org/wiki/Fluent_interface#PHP)) and updated models for SharePoint and Graph APIs

**Comment by ChangingTerry** [comment]
Thanks @vgrem thats good to know.

Will the interface change signficantly?

**Comment by vgrem** [comment]
@ChangingTerry, not really, at least all the existing public API should stay unaffected (for backward compatibility), most of the changes will be introduced via new public types, methods and properties. For example:

- `ClientContext.executeQuery()  `  - the existing (default) method to submit queries to the server

- `ClientContext.executeQueryRetry()  `  - a new method,  extends `ClientContext.executeQuery` in a way to support retry pattern

- `ClientContext.executeBatch()  `  - new method to submit batch queries to the server

**Comment by ChangingTerry** [comment]
Excellent thanks
