### ISSUE TITLE
How Do You Return The Members Of A SharePoint Group

### ISSUE THREAD

**Issue by louieuow** [vgrem/phpSPO#200]
Hello,
Connecting to SharePoint Online,  I am trying to retrieve  the members of a SharePoint Group (say ID 108). I can write code to retrieve all the names and ID number of the Site Groups and I can retrieve all the site users. But I am unable to retrieve members of individual SharePoint groups.
My ultimate gold is output the members of each Group, and then output all the User/Group assignments to Sites, Sub-sites , document libraries and Lists, to try to clean up 12 years of badly assigned access to our large made by previous admins.

This is a fantastic resource but I find it hard to use due to the lack of example code in the areas I need to work with/

This is my attempt at reading group members below from a certain group.

require_once __DIR__ . '/vendor/autoload.php';
$settings = include( __DIR__ . '/vendor/vgrem/php-spo/Settings.php');
use Office365\Runtime\Auth\UserCredentials;
use Office365\SharePoint\ClientContext;
use Office365\SharePoint\Group;
use Office365\SharePoint\GroupCollection;
$credentials = new UserCredentials($settings['UserName'], $settings['Password']);
$ctx = (new ClientContext($settings['Url']))->withCredentials($credentials);
$grpColl = new GroupCollection($ctx);
$grp =  $grpColl->getById(108);    // group number 108
$list = $grp->getUsers();
$ctx->executeQuery(); //submit query to SharePoint Online REST service

print_r($list); // just want to see all the output here  before processing.

**Comment by vgrem** [comment]
Greetings @louieuow,

you were very close, here is a complete example which demonstrates how to _load group users_ with comments: 


```php

$webUrl = "https://{tenant}.sharepoint.com";
$credentials = new UserCredentials("{username}", "{password}");

$client = (new ClientContext($webUrl))->withCredentials($credentials);

$users = $client->getWeb()->getSiteGroups()->getById($groupId)->getUsers();  //1. address a group's users
$client->load($users);  //2. prepare a query to retrieve users, this step is mandatory here `getUsers` is not the actual operation here   
$client->executeQuery(); //3. submit a query to retrieve users

/** @var User $user */
foreach ($users as $user){
    printf($user->getEmail());
}   
```
