### ISSUE TITLE
Executing SPSiteManager queries like Site creation with phpSPO.

### ISSUE THREAD

**Issue by pich** [vgrem/phpSPO#202]
I would like to create a SharePoint site with phpSPO. 
https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest

But I can not find a way to execute a raw JSON query via phpSPO. 
Am I not getting something or this feature is not implemented yet?

**Comment by vgrem** [comment]
Greetings!

Positive. Building a custom requests is supported.


The foloowing example demonstrates how to convert [Create a modern site](https://docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest) endpoint: 

```
url: /_api/SPSiteManager/create
accept: application/json;odata.metadata=none
odata-version: 4.0
method: POST
body:
{
  "request": {
    "Title": "Communication Site 1",
    "Url":"https://contoso.sharepoint.com/sites/commsite1",
    "Lcid": 1033,
    "ShareByEmailEnabled":false,
    "Classification":"Low Business Impact",
    "Description":"Description",
    "WebTemplate":"SITEPAGEPUBLISHING#0",
    "SiteDesignId":"6142d2a0-63a5-4ba0-aede-d9fefca2c767",
    "Owner":"owner@yourtenant.onmicrosoft.com"
  }
}
```

```php

use Office365\Runtime\Auth\ClientCredential;
use Office365\Runtime\Http\RequestOptions;
use Office365\Runtime\ResourcePath;
use Office365\SharePoint\ClientContext;
use Office365\SharePoint\Web;

try {
    $credentials = new ClientCredential($settings['ClientId'], $settings['ClientSecret']);
    $ctx = (new ClientContext($settings['Url']))->withCredentials($credentials);

    $url = "{$ctx->getBaseUrl()}/_api/SPSiteManager/create";
    $request = new RequestOptions($url);
    $payload = array(
        "request" => array(
            "Title" => "Communication Site 1",
            "Url" => "{$ctx->getBaseUrl()}/sites/commsite2",
            "Lcid" => 1033,
            "ShareByEmailEnabled" => false,
            "Classification" => "Low Business Impact",
            "Description" => "Description",
            "WebTemplate" => "SITEPAGEPUBLISHING#0",
            "SiteDesignId" => "6142d2a0-63a5-4ba0-aede-d9fefca2c767",
            "Owner" => "jdoe@contoso.onmicrosoft.com"
        )
    );
    $request->Data = json_encode($payload);
    $resp = $ctx->getPendingRequest()->executeQueryDirect($request);
    $json = json_decode($resp->getContent(), true);
    print("Site has been created: {$json["d"]["Create"]["SiteUrl"]} \n");
}
catch (Exception $e) {
    echo 'Failed: ',  $e->getMessage(), "\n";
}
```

**Comment by pich** [comment]
Thanks, @vgrem such a complete answer with code snippet is more than I could expect. You ROX!

**Comment by pich** [comment]
Hello again @vgrem 
I am getting In ClientRequest.php line 207:
  [Office365\Runtime\Http\RequestException (403)]
  HTTP/2 403
`{"error":{"code":"-2130575251, Microsoft.SharePoint.SPException","message".....`

Could you provide me with some hits? 


It's worth to mention that _api/SPSiteManager/status works like a charm with the same code base, and client IT claims for the last two weeks that it's not a permission issue.

**Comment by christian-kienzl** [comment]
Hi, 

do you have an solution for this problem? I have the same issue!

thx

**Comment by pich** [comment]
@christian-kienzl, unfortunately not. The client's IT claim everything is ok on their side. I've stuck at this point. If you manage to solve this puzzle, please share some tips.

**Comment by christian-kienzl** [comment]
@pich thx for response. yes sure absolute! I am able to create folders an upload files, everything no problem but creating a site. my guess is that the headers in the request are not clean or not set at all and that's why it doesn't work. But I will test this, because the other operations work.

**Comment by pich** [comment]
@christian-kienzl. This is a very good hypothesis. Have you tried to send the manually crafted request from CLI curl with headers set exactly as in Microsoft documentation?

**Comment by christian-kienzl** [comment]
@pich i found an way to create a subsite

$info = new WebCreationInformation('url-name', 'subsite title');
$targetWeb = $ctx->getWeb()->getWebs()->add($info);
$ctx->executeQuery();

try this!

**Comment by pich** [comment]
I will try tomorrow.
