### ISSUE TITLE
Getting SharePoint upload progress from uploadSessions

### ISSUE THREAD

**Issue by DocCobra** [vgrem/phpSPO#203]
Hi! 
Apparently I cannot manage to get updates to the upload progress during an uploadsession to SharePoint. 
I'm using the code as from the UploadLargeFile example, but the chunkUploaded function only fires once, when the upload is finished, returning a single chunksize bytes uploaded. Not useful for large file uploads. 

Is there a way I can get the current status of the actually uploaded bytes to SharePoint? I don't mind using alternative solutions like storing values in a db while it's uploading. Thanks in advance.

**Comment by DocCobra** [comment]
After a while of sifting through the source, I managed to fix it in a way. 
In the buildQuery function inside of UploadSession.php, when the chunkUploaded callable is passed, it's passed with the default parameter to the afterExecuteRequest event handler of $once = true. Overriding it makes it fire when each request is actually completed, so inside of the callback I can update a database field with the upload value of the current session and then poll it asynchronously. Reference: 
```
…
if ($chunkUploaded) {
  $ctx->getPendingRequest()->afterExecuteRequest(function (Response $response) use($chunkUploaded,$ctx)
  {
    $query = $ctx->getCurrentQuery();
    $returnType = $query->ReturnType;
    if($returnType instanceof ClientResult) {
      call_user_func($chunkUploaded, $returnType->getValue());
    }
    elseif ($returnType instanceof File) {
      call_user_func($chunkUploaded, $returnType->getLength());
    }
  }, false); // <<<
}
```

**Comment by vgrem** [comment]
Greetings @DocCobra,


Regarding the question:

> Is there a way I can get the current status of the actually uploaded bytes to SharePoint? 

positive, this scenario is supported, `File.Collection.createUploadSession($sourcePath, $targetFileName,callable $chunkUploaded)`  method accepts a third argument `$chunkUploaded` which represents a callback triggered once chunk is uploaded

Here is an example:

 ```php

    $creds = new ClientCredential($clientId, $clientSecret');
    $ctx = (new ClientContext($url))->withCredentials($creds);
    $localPath = "../data/big_buck_bunny.mp4";
    $targetLibraryTitle = "Documents";
    $targetList = $ctx->getWeb()->getLists()->getByTitle($targetLibraryTitle);

    $session = $targetList->getRootFolder()->getFiles()->createUploadSession($localPath, "big_buck_bunny.mp4",
    function ($uploadedBytes) {
        echo "Progress: $uploadedBytes bytes uploaded .." . PHP_EOL;
    });

    $ctx->executeQuery();
    $targetFileUrl = $session->getFile()->getServerRelativeUrl();
    echo "File $targetFileUrl has been uploaded.";

```

**Output**

![image](https://user-images.githubusercontent.com/1596072/94776232-0493bc00-03ca-11eb-9a98-ed23941dc2f9.png)

**Comment by DocCobra** [comment]
Yeah! I got that from the example, but unfortunately, to me, that method only fired once when the whole transaction of the upload was completed. I had to pass "false" as the argument for the $once parameter as I specified in my second answer above. Once I did that, it started behaving like you mentioned. Thanks for taking the time to answer! :)
