### ISSUE TITLE
undefined index results

### ISSUE THREAD

**Issue by gabrielMoran23** [vgrem/phpSPO#206]
i think im doing something wrong, but i dont know wats the reason for this error

**Comment by vgrem** [comment]
Hey @gabrielMoran23 , could you elaborate a bit, the way how question phrased it is unclear what might cause the error?

**Comment by gabrielMoran23** [comment]
Hello i didnt know what was the error so i created a new sharepoint account to solve it and it worked, i think i was wrong on my sharepoint url folder or somenthing like that.

**Comment by vgrem** [comment]
Good to know! 

Then closing this one since could not be no longer reproduced.
