### ISSUE TITLE
composer 2 compatibility

### ISSUE THREAD

**Issue by rvitaliy** [vgrem/phpSPO#209]
composer version 2.0.6

execute: `composer dump-autoload --optimize --no-dev --classmap-authoritative`

output:
```
Generating optimized autoload files (authoritative)
Class Office365\Graph\Identity located in ./vendor/vgrem/php-spo/src/Graph/ObjectIdentity.php does not comply with psr-4 autoloading standard. Skipping.
```

**Comment by rvitaliy** [comment]
i think it's a bug.

i see that the file `src/Graph/Identity.php` and have a different content.
probably currently the content of ObjectIdentity is never used, because it's in conflict with Identity.

**Comment by rvitaliy** [comment]
@vgrem I think you made a mistake in assigning the label. it's a bug not a question.

**Comment by vgrem** [comment]
Greetings @rvitaliy,

indeed a bug, thank you for catching it!  
Seems class declaration name ambiguity for class generated from model has been resolved.

**Comment by rvitaliy** [comment]
@vgrem thanks you for the fix!
can you release a new hotfix tag, this bug impact my environment, i'll be hope to have this fix in production as soon.
