### ISSUE TITLE
packagist does not create latest tag dist

### ISSUE THREAD

**Issue by rvitaliy** [vgrem/phpSPO#211]
https://packagist.org/packages/vgrem/php-spo
@vgrem can you check if repository is configured correctly?
Thanks!

**Comment by vgrem** [comment]
@rvitaliy, packagist seems to refuse picking up a new release v2.2.3 from GitHub so far, the following message is getting displayed in dashboard page:

> This package is not auto-updated.
> Last update: 2020-11-12 07:47:25 UTC

Running `composer validate` does not reveal any issues with package.

**Comment by rvitaliy** [comment]
@vgrem try to re-configure, see https://github.com/composer/packagist/issues/834

**Comment by rvitaliy** [comment]
any update?

**Comment by vgrem** [comment]
2.4.3 version finally has been propagated to [packagist](https://packagist.org/packages/vgrem/php-spo)
