### ISSUE TITLE
Example read files in folder in SP365

### ISSUE THREAD

**Issue by danielraknes** [vgrem/phpSPO#218]
Question: Do you have an example on how to list files in a folder in SharePoint 365?

**Comment by vgrem** [comment]
Greetings,

the following example demonstrates how  to read files within a folder:


```
$rootFolder = $ctx->getWeb()->getFolderByServerRelativeUrl("Shared Documents/Archive")->expand("Files")->get();
$ctx->executeQuery();

/** @var File $file */
foreach ($rootFolder->getFiles() as $file){
     //...
 }
```

> Note: files from _subfolders_ are not getting returned here

**Comment by RajuSysalgo** [comment]
![image](https://user-images.githubusercontent.com/88371422/200470479-5a1c1eb9-d33c-4c6f-90ef-2c26647f4202.png)

This Bank Statements folder contains columns like name , phone, file ...etc
please help me to get these details.

How can i get  files from subfolders?
