### ISSUE TITLE
old SharePoint complaints about missing or invalid accept header

### ISSUE THREAD

**Issue by blizzz** [vgrem/phpSPO#222]
I have recently seen an instance of SharePoint 2013 (could not reproduce with a test on azure though) that sends our error messaged about an invalid or missing HTTP ACCEPT header. The problem was that `"application/json; OData=verbose"` was sent, but only `"application/json; odata=verbose"` was accepted. The fix was to `strtolower` the return value of `getMediaType()` in the JSonLightSerializerContext (should be Formatter now). 

Would it be acceptable to strtolower the Accept-Header in `Runtime/OData/ODataRequest.php` or is it too hacky, weird o might create side effects elsewhere?

(Feels like a bug somewhere in SP2013 though as those headers should not be case sensitive)

**Comment by vgrem** [comment]
Indeed, seems to be specific to SharePoint 2013 REST Service implementation, and no mention off case (in)sensitivity in [OData Version 3.0 spec](https://www.odata.org/documentation/odata-version-3-0/json-verbose-format/)    

Thanks for the PR!
