### ISSUE TITLE
Returning null for file name when fetching all files from sharepoint

### ISSUE THREAD

**Issue by FCulig** [vgrem/phpSPO#224]
I want to fetch all file names from my sharepoint with following code:
`
$ctx = ClientContext::connectWithUserCredentials($url, $userName, $password);

        $list = $ctx->getWeb()->getLists()->getByTitle("Documents");
        $items = $list->getItems();
        $ctx->load($items);
        $ctx->executeQuery();

        print $items->getCount() . PHP_EOL;
        foreach ($items as $index => $item) {
            //print_r($item);
            print($index . ":" . $item->getProperty('Name') . PHP_EOL);
        }
`

But in print_r it is not returning my file name:
![image](https://user-images.githubusercontent.com/36075622/111541794-367abe00-8771-11eb-8dfb-1386e5bfd297.png)

When obviously all files in SharePoint have their names set:
![image](https://user-images.githubusercontent.com/36075622/111541891-4db9ab80-8771-11eb-9408-d737232c430a.png)
![image](https://user-images.githubusercontent.com/36075622/111541931-5f02b800-8771-11eb-9c4f-42a668e2eca5.png)

**Comment by fabio-carvalho88** [comment]
Have you succeeded in solvind this problem? 

I'm having the same issue. I'm new to php and sharepoint connection, but in your print you show a "documents library" and not a list. Doesn't that make difference since we're using code to fetch items from a list?

**Comment by vgrem** [comment]
Greetings!

`getItems` method returns [`ListItemCollection` resource](https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-csom/ee544394(v=office.15)) while `Name` property is exposed via `File `resource, meaning there is no `Name` property associated with `ListItem`.

To retrieve Name per `ListItem`,  `FileLeafRef` property could be utilized instead which could be retrieved as demonstrated below:  


```php 

$list = $ctx->getWeb()->getLists()->getByTitle($listTitle);
$items = $list->getItems();
$ctx->load($items,["FileLeafRef"]);
$ctx->executeQuery();

/** @var ListItem $item */
foreach ($items as $item) {
    print($item->getProperty("FileLeafRef") . "\r\n");
}

```

or via fluent syntax:


```php

$list = $ctx->getWeb()->getLists()->getByTitle($listTitle);
$items = $list->getItems()->select("FileLeafRef")->get()->executeQuery();

```
