### ISSUE TITLE
 Undefined offset when calling getProperty

### ISSUE THREAD

**Issue by jasonalsing** [vgrem/phpSPO#239]
For instance, when I read a Sharepoint list and subsequently access the item through "getProperty()" function call:

print($item->getProperty($key) . PHP_EOL) ;

i receive the error:

Notice: Undefined offset: 1 in D:\phpSPO\src\Runtime\ClientObject.php on line 267

In the output. It does not impact the retrieval of data but I'm retrieving a lot of items and so I have a lot of these printouts before the data is output to the screen. Any way to avoid this (without changing error_reporting or display_errors within PHP)

**Comment by pongpitis** [comment]
i also have this problem. is there any work around for this bug?

**Comment by vgrem** [comment]
Greetings,

thank you for catching it, it confirmed to be a bug with `ClientObject.getProperty` method. 
Starting from [`2.5.3` version](https://github.com/vgrem/phpSPO/tree/v2.5.3) the provided warning should no longer appear. 

Related issues: #269, #264
