### ISSUE TITLE
Is there any way to check of a folder exists?

### ISSUE THREAD

**Issue by RigidCollision** [vgrem/phpSPO#241]
Hi, 
Having great fun with this API.
Is there a way of checking for existance of a folder in a parent please?

Tried getExists but no joy!

**Comment by vgrem** [comment]
Hi there!


To determine whether folder exists the following approach could be considered: 


```php

$nonExistentFolderUrl = "/sites/team/archive";
$folder = $ctx->getWeb()->getFolderByServerRelativeUrl($nonExistentFolderUrl)->select(["Exists"])->get()->executeQuery();
if(!$folder->getExists()){
    print_r("Folder {$nonExistentFolderUrl} has not been found");
} 
```

Note: _explicitly_ specifying `Exists` property via `select `method does the trick here, this way SharePoint API will not complain with `System.IO.FileNotFoundException` exception.

Same rule applies to `File `resource.
