### ISSUE TITLE
Are there limitations in SharePoint Online ('files per hour', for example)

### ISSUE THREAD

**Issue by Gennady-G** [vgrem/phpSPO#245]
Hi Vadim!

This is a question, not bug. Are there any known limitations for SharePoint Online + Your library? We are going to use SharePoint with Retention policies + external site with Your phpSPO , and hope there will be millions of documents. We know about threshold/max items, and Flow best practices.. Don't You know any pitfalls or limitations related with phpSPO API?

Best regards, Gennady

**Comment by vgrem** [comment]
Greetings Gennady!

arguably the major _limitations_ are:
 - close to zero support for [batch requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis) which which in terms of performance might bring a huge boost(expected to land in the next version of library) 
-  in terms of REST API coverage, rather limited support for modern namespace ([`OfficeDevPnP.Core.Pages` Namespace](https://docs.microsoft.com/en-us/dotnet/api/officedevpnp.core.pages?view=sharepoint-pnpcoreol-3.2.1810))  
-  no provision engine support ([PnP provisioning engine](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine))

**Comment by Gennady-G** [comment]
Thank You much Vadim! Your library is great!)

Best regards, Gennady
