### ISSUE TITLE
Looking for an example for FieldMultiChoice

### ISSUE THREAD

**Issue by xmartinj** [vgrem/phpSPO#246]
Apologize for the newbie question. I'm trying to alter a multichoice status field.

**Comment by AnthonyScorch** [comment]
Same issue, it cant really as they need to be passed as objects.

**Comment by AnthonyScorch** [comment]
You should get the following error:  An open collection property ### was found. In OData, open collection properties are not supported.

**Comment by vgrem** [comment]
Greetings,

starting from [`2.5.3` version](https://github.com/vgrem/phpSPO/tree/v2.5.3) the support for working with multi-valued choice fields has been enhanced.

`FieldMultiChoiceValue` type has been introduced and the following example demonstrate how  to create a list item and specify multi-choice field value:

```php

$list = $ctx->getWeb()->getLists()->getByTitle("Tasks");

$taskProps = array(
    'Title' => "New task",
    'TaskCategories' => new FieldMultiChoiceValue(["Event", "Reminder"])
);
$item = $list->addItem($taskProps)->executeQuery();
```

_where   `TaskCategories` is a name for  multi-valued-choice field_
