### ISSUE TITLE
Check if specific file exists

### ISSUE THREAD

**Issue by F4T4LERROR** [vgrem/phpSPO#262]
In June vgrem posted in another thread about checking if a Folder exists:

> To determine whether folder exists the following approach could be considered:
> 
> ```
> $nonExistentFolderUrl = "/sites/team/archive";
> $folder = $ctx->getWeb()->getFolderByServerRelativeUrl($nonExistentFolderUrl)->select(["Exists"])->get()->executeQuery();
> if(!$folder->getExists()){
>     print_r("Folder {$nonExistentFolderUrl} has not been found");
> } 
> ```
> 
> Note: _explicitly_ specifying `Exists` property via `select `method does the trick here, this way SharePoint API will not complain with `System.IO.FileNotFoundException` exception.
> 
> Same rule applies to `File `resource.

However, if I modify getFolderByServerRelativeUrl to getFileByServerRelativeUrl and then use a relative URL filepath such as
$nonExistentFileUrl = "/sites/SITENAME/Shared Documents/test/nosuchfile.jpg";  for a file, **it only runs successfully if the file exists**. 

 If it doesn't exist, I get an error such as:
Fatal error: Uncaught Office365\Runtime\Http\RequestException: {"error":{"code":"-2130575338, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The file /sites/SITENAME/Shared Documents/test/nosuchfile.jpg does not exist."}}}

I must be doing something wrong, but am not sure what.  My code is exactly what vgrem supplied, just modified for a file:

`$nonExistentFileUrl = "/sites/SITENAME/Shared Documents/test/nosuchfile2.jpg";
$file = $ctx->getWeb()->getFileByServerRelativeUrl($nonExistentFileUrl)->select(["Exists"])->get()->executeQuery();
if($file->getExists()){
    print_r("File {$nonExistentFileUrl} has been found");
} else if(!$folder->getExists()){
    print_r("File {$nonExistentFileUrl}} has not been found");
} `

**Comment by vgrem** [comment]
Greetings, 

thank you for catching this issue, i confirm this approach indeed does not seem applicable for `file` resource.

The following approach could be considered to determine whether file exist:  


```php
$fileUrl = "/sites/team/Shared Documents/Archive/Sample.docx";
$file = $ctx->getWeb()->getFileByServerRelativeUrl($fileUrl);
try {
    if (!tryGetFile($file)) {
        echo "File not found:", $fileUrl;
    }
    echo $file->getName();
} catch (Exception $e) {
    echo "An error occurred:", $e->getMessage();
}

```


where 


```php
/**
 * @param File $file
 * @throws RequestException
 */
function tryGetFile($file){
    try {
        $file->get()->executeQuery();
    }
    catch (RequestException $ex){
        if($ex->getCode() === 404){    // Is File Not Found exception type?
            return false;
        }
        throw $ex;
    }
    return true;
}

```
