### ISSUE TITLE
Stack trace called unnecessarily

### ISSUE THREAD

**Issue by peterhropko** [vgrem/phpSPO#264]
https://github.com/vgrem/phpSPO/blob/dc6c82d8891310ea2a0fa27fc2b67cfb80185d4d/src/Runtime/ClientObject.php#L267

This can be called right before the place where it is used (line 273). Otherwise it makes queries for stacktrace on each getProperty request which makes it very slow.

**Comment by ricardovigatti** [comment]
Is this related to #269 ?

This looks odd to me:
```
public function getProperty($name,$defaultValue=null)
{
    $calledFnName = debug_backtrace()[1]['function'];    
    [ ... ]
 }
```

**Comment by vgrem** [comment]
Hey guys,
 
starting from [`2.5.3` version](https://github.com/vgrem/phpSPO/tree/v2.5.3) `getProperty` method has been optimized in terms of dropping `debug_backtrace` method usage.
