### ISSUE TITLE
SharePoint List Author

### ISSUE THREAD

**Issue by drkkvfulda** [vgrem/phpSPO#268]
Hi, everyone,

I can't get the author to be displayed in the items of a sharepoint list. I only see AuthorId in the array.

Thank you.

**Comment by vgrem** [comment]
Greetings,

this is _expected_ behavior (by SharePoint API design, namely for user fields, only identifier is getting returned by default), `Author` needs to be _explicitly_ requested via `$expand` query option. The  following example demonstrates how to retrieve list items  with `Author` field values and print `Author.Name`:



```php
$credentials = new ClientCredential($ClientId, $ClientSecret);
$ctx = (new ClientContext($siteUrl))->withCredentials($credentials);

$list = $ctx->getWeb()->getLists()->getByTitle("Documents");
$items = $list->getItems()->select(["Author/Name", "Author/Title","FileRef"])->expand(["Author"])->get()->top(10)->executeQuery();

/** @var ListItem $item */
foreach ($items as $item){
    print("Url:" . $item->getProperty('FileRef') .  " Author:" . $item->getProperty('Author')["Name"] . PHP_EOL);
}

```


### References

[Use OData query operations in SharePoint REST requests](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests)
