### ISSUE TITLE
getProperty gives a warning

### ISSUE THREAD

**Issue by bally86** [vgrem/phpSPO#269]
Hi,

I try to get a list of all folders. When I read the property Name with getProperty it gives the warning below. The Name echos correctly so it all seems to work. But why the warning?

$folders = $ctx->getWeb()->getFolderByServerRelativeUrl("/*****")->getFolders();

$ctx->load($folders);
$ctx->executeQuery();

foreach ($folders->getData() as $folder) {
    echo $folder->getProperty('Name') . "<br/>";
}

Warning: Trying to access array offset on value of type null in \vendor\vgrem\php-spo\src\Runtime\ClientObject.php on line 267

**Comment by ricardovigatti** [comment]
Same issue here, whats going on?
