### ISSUE TITLE
How to sort results?

### ISSUE THREAD

**Issue by ricardovigatti** [vgrem/phpSPO#275]
I'm using the following piece of code to retrieve files and folders from a relative path:

```php
/** @var \Office365\SharePoint\Folder */
$folder = $this->context->getWeb()->getFolderByServerRelativeUrl($builtPath)->expand(['Files', 'Folders'])->get()->executeQuery();

/** @var \Office365\SharePoint\FolderCollection */
$folders = $folder->getFolders();

/** @var \Office365\SharePoint\FileCollection */
$files = $folder->getFiles();
```

How can I sort results in a specific order? Let's say, by Name or by date of creation?

**Comment by vgrem** [comment]
Greetings,

per [Sort returned items](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-odata-query-operations-in-sharepoint-rest-requests#sort-returned-items):

> Use the [$orderby](http://www.odata.org/documentation/odata-version-2-0/uri-conventions#OrderBySystemQueryOption) query option to specify how to sort the items in your query return set. To sort by multiple fields, specify a comma-separated list of fields. You can also specify whether to sort the items in ascending or descending order by appending the asc or desc keyword to your query.


Here is an example, namely sorting files by `Name` property in _ascending_ order:


```php
$folderPath = "Shared Documents";
$files = $ctx->getWeb()->getFolderByServerRelativeUrl($folderPath)->getFiles()->orderBy("Name asc")->get()->executeQuery();
/** @var File $file */
foreach ($files as $file){
    print "File name {$file->getName()} \r\n";
}
```
