### ISSUE TITLE
Too few arguments to function Office365\SharePoint\ClientContext::__construct(), 1 passed and exactly 2 expected

### ISSUE THREAD

**Issue by nunosilvafullscreen** [vgrem/phpSPO#277]
Hello

First of all thanks for the hard work.

I've tried using the sharepoint API but I got an error when trying to connect with the user credentials auth:
Too few arguments to function Office365\SharePoint\ClientContext::__construct(), 1 passed and exactly 2 expected

my code is exactly like the documentation:
$credentials = new UserCredentials("{userName}", "{password}");
$ctx = (new ClientContext("{siteUrl}"))->withCredentials($credentials);

**Comment by cweiske** [comment]
This does only happen if you are using a version before v2.4.2.
The second parameter was made optional in commit ac56daf77f9e24b893ccf1040419c01dbd1a4c93, which has been released with v2.4.2.

So simply update to v2.4.2 or later.
