### ISSUE TITLE
 Unable to download file as stream from SharePoint with ServerRelativeUrl

### ISSUE THREAD

**Issue by la-costa** [vgrem/phpSPO#284]
I'm having trouble downloading files by stream, maybe because it has a server relative url.

```php
<?php

$siteUrl = "https://organization.sharepoint.com";
$relativeUrl = "/sites/<site-name>";        

$username = "USERNAME";
$password = "PASSWORD";
$credentials = new UserCredentials("{$username}", $password);
$client = (new ClientContext("{$siteUrl}{$relativeUrl}"))->withCredentials($credentials);

$rootFolder = $client
    ->getWeb()
    ->getFolderByServerRelativeUrl('Documents')
    ->expand('Files')
    ->get()
    ->executeQuery()
;

// This works perfectly
print "==> List Files:\r\n";
/** @var File $file */
foreach ($files as $file) {
    print "Filename: {$file->getName()}\r\n";
}

// This works perfectly
print "==> Download as content:\r\n";
foreach ($files as $file) {
    try {
        $sourceFileUrl = "{$relativeUrl}/Documents/{$file->getName()}";
        $fileContent = File::openBinary($client, $sourceFileUrl);
        $fileName = join(DIRECTORY_SEPARATOR, [sys_get_temp_dir(), $file->getName()]);
        file_put_contents($fileName, $fileContent);
        print "Filename: {$file->getName()}\r\n";
    } catch (\Throwable $th) {
        print "Error {$th->getCode()} - File download failed: {$th->getMessage()}";
    }
}        

// This one DOESN'T WORK
print "==> Download as stream:\r\n";
foreach ($files as $file) {
    try {
        $fileName = join(DIRECTORY_SEPARATOR, [sys_get_temp_dir(), $file->getName()]);
        $fh = fopen($fileName, 'w+');
        $file->download($fh);
        $client->executeQuery();
        fclose($fh);
        print "Filename: {$file->getName()}\r\n";
    } catch (\Throwable $th) {
        print "Error {$th->getCode()} - File download failed: {$th->getMessage()}";
    }
}
```

In the phpSPO project if I comment out the lines of `php-spo\src\SharePoint\Web.php` the execution works correctly.

```php
public function getResourceUrl()
{
    $url = parent::getResourceUrl();
    // if (!is_null($this->webUrl)) {
    //     return str_replace("/_api/", "{$this->webUrl}/_api/", $url);
    // }
    return $url;
}
```

What I noticed is that in the current implementation, the server relative url is duplicated.

:heavy_check_mark: Expected: https:<area>//organization.sharepoint.com/sites/example/_api/Web/getFileByServerRelativeUrl('%2Fsites%example%2FDocuments%2Ftest.pdf')/$value
:x: Received: https:<area>//organization.sharepoint.com/sites/example/**sites/example/**_api/Web/getFileByServerRelativeUrl('%2Fsites%example%2FDocuments%2Ftest.pdf')/$value

**Comment by vgrem** [comment]
Greetings,

thank you for catching this error and providing the detailed analysis!
A new version [`2.5.4`](https://packagist.org/packages/vgrem/php-spo#v2.5.4) has been released where among another improvements this issue has been addressed.

**Comment by RajuSysalgo** [comment]
This code is worked for me 
                
                $sourceFileUrl = '/sites/xyz/Shared Documents/file.jpg';
		$fileContent = File::openBinary($ctx, $sourceFileUrl);
		$fileName = join(DIRECTORY_SEPARATOR, [sys_get_temp_dir(), "sunny.jpg"]);
		print_r($fileName);
		file_put_contents($fileName, $fileContent);

		if (file_exists($fileName)) {
		    header('Content-Description: File Transfer');
		    header('Content-Type: application/octet-stream');
		    header('Content-Disposition: attachment; filename='.basename($fileName));
		    header('Content-Transfer-Encoding: binary');
		    header('Expires: 0');
		    header('Cache-Control: must-revalidate');
		    header('Pragma: public');
		    header('Content-Length: ' . filesize($fileName));
		    ob_clean();
		    flush();
		    readfile($fileName);
		    unlink( $fileName );
		    exit;
		}
