### ISSUE TITLE
Is this ready for PHP8?

### ISSUE THREAD

**Issue by JeppeDonslund** [vgrem/phpSPO#293]
I get this error

Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/www.myDomain.dk/vendor/vgrem/php-spo/src/Runtime/Http/Requests.php on line 137

So I thought, is phpSPO ready for PHP 8?

**Comment by cweiske** [comment]
@vgrem This can be closed.
