### ISSUE TITLE
Get multiple value field

### ISSUE THREAD

**Issue by radem205** [vgrem/phpSPO#30]
Hi,

I try to get the multiple selected values of a field called 'Docset'. Therfore I use the code below;

```
$items = $list->getItems()->select('Title,EncodedAbsUrl,Documentstatus,Docset/Title')->expand('Docset/Title')->filter("Docset eq 5 and Documentstatus ne 'Te verwijderen' and Documentstatus ne 'Vervallen'")->orderby('Title');  //apply filter query option
	$ctx->load($items);
	$ctx->executeQuery();
	foreach( $items->getData() as $item ) {
var_dump($item->Docset);
		print 'Task: <a href="'.$item->EncodedAbsUrl.'" target="_blank">'.$item->Title.' ('.$item->Documentstatus.')</a> '.$item->Docset->results[0]->Title<br />';
	}
```

The var dump in the code above returns NULL. Also the title of the Docset isn't displayed.

When I execute the url below, the Docset title is presented in the output.

https://bla.sharepoint.com/sites/bla/_api/Web/Lists/getByTitle('Documenten')/items?$select=Title,EncodedAbsUrl,Docset/Title&$expand=Docset/Title&$filter=Docset%20eq%205

I don't know what I'm doing wrong. Maybe you can help me guys.

Thanks.

**Comment by dalmatele** [comment]
You can fix that by:
- Add this line to Office365\PHP\Client\Runtime\OData\JsonPayloadSerializer.php:

> require_once '../libs/OutlookServices/Subscription.php';

and change convertToClientObject function to this:
----------

> function convertToClientObject(stdClass $item,ClientObject $targetObject)
>     {
>         foreach ($item as $key => $value) {
>             if ($this->isMetadataProperty($key)) {
>                 continue;
>             }
>             if (is_object($value)) {
>                 
>                 if ($this->isDeferredProperty($value)) { //deferred property
>                     $targetObject->setProperty($key,null,false);
>                 }
>                 else {
>                     $propertyObject = $targetObject->getProperty($key);
>                     if(empty($propertyObject)){
>                         $propertyObject = new \Office365\PHP\Client\OutlookServices\Subscription($targetObject->getContext());
>                         $targetObject->setProperty($key, $propertyObject);
>                     }
>                     $propertyObject = $targetObject->getProperty($key);
>                     if ($propertyObject instanceof ClientObject) {
>                         $this->convertToClientObject($value,$propertyObject);
>                     }else{
>                         
>                     }
>                 }
>             }
>             else {
>                 $targetObject->setProperty($key,$value,false);
>             }
>         }
>     }
And last, you add to  Subscription file:

> require_once '../libs/Runtime/ClientObject.php';
> 
> use Office365\PHP\Client\Runtime\ClientObject;

Yeah, now you can access it by this way:
$item->Docset->results->Title

**Comment by vgrem** [comment]
Greetings!

The issue with getting projected properties has been finally resolved. Thank you all for a detailed description and the proposed quick fix.  

**Here are a few examples**


1) Getting user _single_ field value 


    $items = $targetList->getItems(CamlQuery::createAllItemsQuery())
            ->select("AssignedTo/Title")
            ->expand("AssignedTo");
    $context->load($items);
    $context->executeQuery();

    if($items->getCount() > 0){
            $item = $items->getItem(0);
            $assignedTo = $item->getProperty("AssignedTo");
            print $assignedTo->Title;
    }


2) Getting user _multiple_ field value 


    $items = $targetList->getItems(CamlQuery::createAllItemsQuery())
            ->select("Predecessors/Title")
            ->expand("Predecessors");
    $context->load($items);
    $context->executeQuery();

    if($items->getCount() > 0){
            $item = $items->getItem(0);
            $predecessors = $item->getProperty("Predecessors");
            if(count($predecessors->results) > 0)
                print $predecessors->results[0]->Title;
           
    }
