### ISSUE TITLE
can not get value of child items if using expand function

### ISSUE THREAD

**Issue by dalmatele** [vgrem/phpSPO#31]
I had this code:
$list->getItems()
                    ->select("BuyerName,BuyerTitle,BuyerAddress,BuyerMobile,TrackingCodeTitle,"
                            . "BuyerPostalCode,Amount,ServiceCode/ServiceCode,Advisor/Title,CourseCode/Title")
                    ->expand("ServiceCode,Advisor,CourseCode")
                    ->filter($filter)
                    ->top(1);
But, I can not get $item->Advisor[0]->Title.
As I saw in your code JsonPayloadSerializer.php:
in convertToClientObject function had this line code:
else {
                    $propertyObject = $targetObject->getProperty($key);
....
It's alway null, so you can get their value.
Can you fix that?

**Comment by vgrem** [comment]
Hi,
the issue with getting projected properties has been finally resolved. 
Thank you for your investigation!

**Here  is the example of getting user _single_ field value 


    $items = $targetList->getItems(CamlQuery::createAllItemsQuery())
            ->select("AssignedTo/Title")
            ->expand("AssignedTo");
    $context->load($items);
    $context->executeQuery();

    if($items->getCount() > 0){
            $item = $items->getItem(0);
            $assignedTo = $item->getProperty("AssignedTo");
            print $assignedTo->Title;
    }
