### ISSUE TITLE
Will UserCredentials be supported after Basic Auth is disabled?

### ISSUE THREAD

**Issue by kleindev** [vgrem/phpSPO#311]
Is the following code snippet still valid after Microsoft disables basic auth for SharePoint Online?

  use Office365\Runtime\Auth\UserCredentials;
  use Office365\SharePoint\ClientContext;

  $credentials = new UserCredentials("{userName}", "{password}");
  $ctx = (new ClientContext("{siteUrl}"))->withCredentials($credentials);

**Comment by vgrem** [comment]
Greetings,

it is, in fact this flow has nothing to do with `Basic` auth, instead it utilizes `Claims Based` scheme.
