### ISSUE TITLE
How to capture multiple data with same Title?

### ISSUE THREAD

**Issue by keanbillyfernandez** [vgrem/phpSPO#314]
Hi, I would like to fetch multiple data but same Title. It is returning only 1 data as of now,.

**Comment by vgrem** [comment]
At least the following options could be considered:

1. Using [`$filter`](https://www.odata.org/documentation/odata-version-2-0/uri-conventions#FilterSystemQueryOption) query option to select which items to return, e.g. `Title eq  '--value-- '`

Example:

```php
$list = $ctx->getWeb()->getLists()->getByTitle("Documents");
$items = $list->getItems()->select(["Title"])->filter("Title eq 'New title'")->get()->executeQuery();
```

2. Using [Caml query](https://learn.microsoft.com/en-us/sharepoint/dev/schema/query-element-list)

```php
$qry = new CamlQuery();
$qry->ViewXml = <<<XML
<View Scope='RecursiveAll'>
    <Query><Where><Eq><FieldRef Name="Title" /><Value Type="Text">New title</Value></Eq></Where></Query>
</View>
XML;
$items = $list->getItems($qry)->executeQuery(); 
```
