### ISSUE TITLE
How to read an sharepoint list that contains more than 5000 items?

### ISSUE THREAD

**Issue by BeginnerRaffe** [vgrem/phpSPO#315]
Hello All,

I have a question. I'm trying to read an list that consist of over 5000 items. I got an error because of the limit. I though if I filter I could read an list with over 5000 items (filtered list less than 5000 items), but that does not work either, I get the same error. My code look like below. Is it possible to read in another way?

$today = date("Y-m-d"); //Today

$web = $client->getWeb();
$list = $web->getLists()->getByTitle("Data"); //init List resource
$filter = "Datum ge '" .  $today  . "'";
$items = $list->getItems()->filter($filter);

$client->load($items);  //save a query to retrieve list items from the server
$client->executeQuery(); //submit query to SharePoint server

**Comment by vgrem** [comment]
When working with a large list with filtering applied, indexing columns  is the most effective way to mitigate View threshold exception.


**Resolution**

goto `List Settings`, click  `Indexed columns` link -> click `Create a new index` link -> choose Datum  as a Primary column for this index and finally  click  `Create` button
  
_The indexing operation might take a few minutes to complete, please wait until `Datum (Indexing in progress)` message will disappear._    
      
  

And last but not least, if `Datum` represents "Date and Time" column, the value  is expected to provided in ISO string format as demonstrated in below example:   

```php

$today = date("c"); //in ISO string format
$filter = "Datum le datetime'" .  $today  . "'";   

$list = $ctx->getWeb()->getLists()->getByTitle("Contacts");
$items = $list->getItems()->get()->filter($filter)->top(5000)->executeQuery();

```


**References**

[Living Large with Large Lists and Large Libraries](https://learn.microsoft.com/en-us/microsoft-365/community/large-lists-large-libraries-in-sharepoint)
