### ISSUE TITLE
\ In folder names cause error with composer autoloader

### ISSUE THREAD

**Issue by thijsvdanker** [vgrem/phpSPO#320]
When trying to update composer throws an error when creating the autoloader:

```bash
composer dump-autoload -o

...

In ClassMapGenerator.php line 158:

  realpath of /path/to/vendor/vgrem/php-spo/src/SharePoint/Sharing/ShareLinkPartialSuccessResponse.php failed to resolve, got false
```
This is because there is a slash in (at least) 3 folder names:

1. https://github.com/vgrem/phpSPO/tree/master/src/SharePoint/%5CPublishing
2. https://github.com/vgrem/phpSPO/tree/master/src/SharePoint/%5CSharing
3. https://github.com/vgrem/phpSPO/tree/master/src/SharePoint/%5CTaxonomy%5CContentTypeSync

**Comment by bkrztuk** [comment]
+1 - please fix

**Comment by Tjeerd** [comment]
Also running into this issue. I suspect this is only a problem when dumping the autoloader in optimized mode (-o or -a).

**Comment by davidhsianturi** [comment]
Same. can't update the composer

`Composer version 2.5.4 2023-02-15 13:10:06`

**Comment by vgrem** [comment]
Greetings,

@thijsvdanker, thank you for catching and reporting it! And last but not least kudos to @menegain-mathieu to create a PR! :+1: 
 

A new [3.0.2 version](https://packagist.org/packages/vgrem/php-spo)  which addresses this issue has been just released.
