### ISSUE TITLE
Access via Azure AD App-Only / certificate

### ISSUE THREAD

**Issue by sommcz** [vgrem/phpSPO#326]
Hello,

i can't find any documented way to authorize with app-only certificate access described below as preferred model.
https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread

Thank you

**Comment by vgrem** [comment]
Greetings,

the  library starting from  [`3.1.0` version](https://github.com/vgrem/phpSPO/releases/tag/v3.1.0) supports _app-only access with client cerificate_, here  is an example:

```php
$siteUrl = "https://contoso.sharepoint.com";  //site or web absolute url 
$tenant = "contoso.onmicrosoft.com"; //tenant id or name
$thumbprint = "--thumbprint goes here--";
$clientId = "--client app id goes here--";
$privateKetPath = "-- path to private.key file--"
$privateKey = file_get_contents($privateKetPath);

$ctx = (new ClientContext($siteUrl))->withClientCertificate(
    $tenant, $clientId, $privateKey, $thumbprint);

$whoami = $ctx->getWeb()->getCurrentUser()->get()->executeQuery();
print $whoami->getLoginName();  
```
 

Refer [wiki page](https://github.com/vgrem/phpSPO/wiki/Granting-access-via-Azure-AD-App%E2%80%90Only-with-Certificate) for a more details

**Comment by cweiske** [comment]
@vgrem thank you for implementing that feature with d167020a84faac69e79fc37b9fffbbd2dd96f98f!

**Comment by vgrem** [comment]
@cweiske, this perhaps was among the most requested features given [SharePoint App-Only auth retirement last year](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs) :)

Thank you for your contrubutions!
