### ISSUE TITLE
cannot install it via composer in command line or composer.json

### ISSUE THREAD

**Issue by orkempire** [vgrem/phpSPO#33]
I keep receiving the error that 

` [InvalidArgumentException]
  Could not find package vgrem/php-spo at any version for your minimum-stability (stable). Check the package
   spelling or your minimum-stability`

...whenever I do `composer require vgrem/php-spo` I have tried it with `--dev` and still get the same problem.

**Comment by vgrem** [comment]
Are you sure there is no spelling errors in your command?
The following command works for me:

`php composer.phar require vgrem/php-spo:dev-master -n --no-progress`

**Comment by orkempire** [comment]
Great, worked fine! I think it would be helpful if a note was added in the installation notes. as without `-n --no-progress` it didn't work.
