### ISSUE TITLE
authenticateRequest but clientId is not registered

### ISSUE THREAD

**Issue by agungsijawir** [vgrem/phpSPO#332]
Hello,

Somehow when the `clientId` is not registered yet, the API returns error. The callback returns something like this:

```JSON
{
"error":"unauthorized_client",
"error_description":"AADSTS700016: Application with identifier '{clientId}' was not found in the directory '{my_company_name}'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. Trace ID: {{GUID_Trace_ID}} Correlation ID: {{GUID_Correlation_ID}} Timestamp: 2023-06-25 15:38:35Z",
"error_codes":[700016],
"timestamp":"2023-06-25 15:38:35Z",
"trace_id":"{{GUID_Trace_ID}}",
"correlation_id":"{{GUID_Correlation_ID}}",
"error_uri":"https:\/\/login.microsoftonline.com\/error?code=700016"}
```

The errors comes from this function: `vgrem\php-spo\src\GraphServiceClient.php` line 157, at function `authenticateRequest`.

Would be nice if we can handle the request errors first and if passes, then continue to next data.

**Comment by vgrem** [comment]
Greetings,
 
thanks for the suggestion, starting from version `3.0.0`, the library contains built-in method to validate token response. 
It is getting called in `authenticateRequest` method and should throw an exception if the token response returns an error.
