### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by MiddleSiggy** [vgrem/phpSPO#343]
Your composer example tells people to install an older version:

{
    "require": {
        "vgrem/php-spo": "^2.4"
    }
}

but this will produce warnings on newer PHP installs around deprecated commands.

You might want to adjust to the newer version. "^3"

Thanks

**Comment by cweiske** [comment]
You fixed it with commit e6d6b4f38d070ca9f7b4cf2877e80fa463a8f384 @vgrem. Please close.
