### ISSUE TITLE
File Upload - Unable to  set property

### ISSUE THREAD

**Issue by rubanjoshva** [vgrem/phpSPO#38]
Hi, 
I trying to upload file with  properties. Here is my code, 
function uploadFiles($localPath, \Office365\PHP\Client\SharePoint\SPList $targetList){
	    $ctx = $targetList->getContext();
	    $searchPrefix = $localPath . '*.*';
	    foreach(glob($searchPrefix) as $filename) {
	        $fileCreationInformation = new \Office365\PHP\Client\SharePoint\FileCreationInformation();
	        $fileCreationInformation->Content = file_get_contents($filename);
	        $fileCreationInformation->Url = basename($filename);
	        $uploadFile = $targetList->getRootFolder()->getFiles()->add($fileCreationInformation);
	        $uploadFile->setProperty('Title','It is a test');//setting the property
	        $ctx->executeQuery();
	        print "File {$uploadFile->getProperty('Name')} has been uploaded\r\n";
	    }
	}
after running this code, I see only the file is uploded, but no property is set. What am I missing here ?

**Comment by vgrem** [comment]
Greetings,

file metadata is not getting updated since you need to target not the file entity itself but associated list item as demonstrated below. 


In order to set  metadata once the file is uploaded, replace the line:

`$uploadFile->setProperty('Title','It is a test');//setting the property`

with

```
$uploadFile->getListItemAllFields()->setProperty('Title',basename($filename)); //update associated list item entity
$uploadFile->getListItemAllFields()->update();  //tell query to update entity
```


where 

`$uploadFile->getListItemAllFields()` returns associated list item entity

**Comment by rubanjoshva** [comment]
Hello Sir, 
Thank you so much. I got it working. But there is one important thing we need to consider, if we run the above code with replacement of your code, we would get this issue "Cannot find resource for the request ListItemAllFields", this is because, we try to update meta data to a list item which does not exists still on SP. So we need to run '$ctx->executeQuery();' first to upload the file, and then set the entity fields, and again run '$ctx->executeQuery();'. Now it is working. 
Here is the comprehensive, working code:
function uploadFiles($localPath, \Office365\PHP\Client\SharePoint\SPList $targetList){
	    $ctx = $targetList->getContext();
	    $searchPrefix = $localPath . '*.*';
	    try{
		    foreach(glob($searchPrefix) as $filename) {
		        $fileCreationInformation = new \Office365\PHP\Client\SharePoint\FileCreationInformation();
		        $fileCreationInformation->Content = file_get_contents($filename);
		        $fileCreationInformation->Url = basename($filename);
		        $uploadFile = $targetList->getRootFolder()->getFiles()->add($fileCreationInformation);
			$ctx->executeQuery();//upload the file
		        $listEntity = $uploadFile->getListItemAllFields(); //now update associated list item entity
			$listEntity->setProperty('Title',"it is a test");
			$listEntity->update(); //tell query to update entity
		       	$ctx->executeQuery();
		        print "File {$uploadFile->getProperty('Name')} has been uploaded\r\n";
		    }
		}catch(Exception $e){echo 'Error : '. $e->getMessage();}
	}

**Comment by vgrem** [comment]
Good to know!

And that's right, file entity should be created first with `$ctx->executeQuery();` and only then get updated.

Best,
Vadim

**Comment by rubanjoshva** [comment]
Hello Sir,
The file uploading is working on my SP server (say 'site-1'), but when I try upload with some other server (say 'site-2') I get this issue "first parameter must either be an object or the name of an existing class" when this statement gets executed '$ctx->executeQuery();'.  It occurs on the file "ODATA/JsonPayloadSerializer.php" at line 52. Why is this occurring only on site-2 as it works on site-1.
The statement '$ctx->executeQuery();' works for other stuffs like getting lists , fields but only fails for uploading. The site-2 is using NTLM authentication and also it is a subsite whereas the site-1 is not. Will it cause the problem ? Thanks.

**Comment by MAdeelTariq** [comment]
please tell me how you get the local file path for uploading that process actually i face some error during that task. 
$filepath =  './data/Desert.jpg'; 
uploadFiles($filepath,$list);
That is my code for get the uploading file path.

**Comment by stuartpaulin** [comment]
Hi, I have just moved to version 2.5.3  and this process has suddenly stopped working.  The code below worked fined until the upgrade.  Has something changed?

`$uploadFile = $this->ctx->getWeb()->getFolderByServerRelativeUrl($targetFolderUrl)->getFiles()->add($fileCreationInformation);
                $this->ctx->executeQuery();

                //print_r($uploadFile->getListItemAllFields()->get()->executeQuery());  // get field names
                $uploadFile->getListItemAllFields()->setProperty('Title', $fileName);
                $uploadFile->getListItemAllFields()->setProperty('ClientNumber', $file['id']);
                $uploadFile->getListItemAllFields()->setProperty('ClientName', $file['venue']);
                //Adjust the date to suit sharepoint standard which is backwards like SQL
                $sharePointDate = \DateTime::createFromFormat('d/m/Y', $file['weekEnding'])->format('Y-m-d');
                $uploadFile->getListItemAllFields()->setProperty('WeekEnding', $sharePointDate);

                $uploadFile->getListItemAllFields()->update();
                $this->ctx->executeQuery();`

**Comment by stuartpaulin** [comment]
ok, this was the answer, I hope it helps some fellow google searcher... 
`$itemMeta = $uploadFile->getListItemAllFields();
                $itemMeta->setProperty('Title', $fileName);
                $itemMeta->setProperty('ClientNumber', $file['id']);
                $itemMeta->setProperty('ClientName', $file['venue']);
                // Adjust the date to suit sharepoint standard which is backwards like SQL
                $sharePointDate = \DateTime::createFromFormat('d/m/Y', $file['weekEnding'])->format('Y-m-d');
                $itemMeta->setProperty('WeekEnding', $sharePointDate);
                $itemMeta->update();
                $this->ctx->executeQuery();`
