### ISSUE TITLE
Consuming "_api/contextinfo" fails due to issue "Http 411 - length required"

### ISSUE THREAD

**Issue by rubanjoshva** [vgrem/phpSPO#39]
Hello Sir,
This is Ruban Joshva again.
When I try uploading files on my SP server(uses NTLM auth), I could not upload the file. When I tried debugging through library I found that, in the file ClientContext.php at line 173 the response is given as "Http 411 - length required" (library trying to consume _api/contextinfo here). But I see the content length is set to 0 in curl.  When I try with one of the other site I am able to get the correct response(content length :0 here too), and able to upload files. When I tried it on REST Client with setting the content length 0, it gives the same response. Why this site is returning this response ? How do I solve this ? Or is there any work around how I can upload the file ?(I am getting issue only when uploading, other functions work fine). And this site(where I face issue) is a SP subsite using NTLM authentication. Thanks.

**Comment by ian-coates** [comment]
Hi rubajoshva I have the same problem!! did you solve it?

Thanks

**Comment by breugela** [comment]
hi, seems to be an issue in the code. Chech the function "addCustomHeader" in the file "RequestOptions.php". I've changed the following:

```
//$this->Headers[$name] = $value;
$this->Headers = array($name, $value); 
```

hope it helps..

**Comment by enocryph** [comment]
solved this by adding to php-spo/src/Runtime/Utilities/Requests.php in the beginning of function **execute()** following code:
```php
if ($options->Method === HttpMethod::Post &&  !array_key_exists('content-length', $options->Headers)) {
    $options->addCustomHeader("Transfer-Encoding", "chunked");
}
```

**Comment by Ozerich** [comment]
Hi, @vgrem, Can you implement fix from @enocryph?
