### ISSUE TITLE
Unable to upload the files to sharepoint lists

### ISSUE THREAD

**Issue by ewallteam** [vgrem/phpSPO#4]
Hi ,
We have used your script to retrieve and update the share point folders and files . But we are unable to download and upload the files by using your class files.Please let me know how to use your script for upload and download the files.

**Comment by nkgokul** [comment]
@ewallteam can you share the code that you used for retrieving and updating sharepoint folders? I am working on folders, download and upload files now. Will share notes once I am done with it.

**Comment by mynamavi** [comment]
Hi ewallteam,
Firstly Thanks for your library, it helps alot.
Can you please tell me how can i upload attachment  and url whose type is hyperlink can be saved in list?

**Comment by wayzz1992** [comment]
Was this issue resolved? I am also having problems uploading files using this script. I am using the example code to try it out.

**Comment by vgrem** [comment]
File resource support the list of operations including:

- [`FileCollection.add(FileCreationInformation $fileCreationInformation)`](https://github.com/vgrem/phpSPO/blob/master/src/SharePoint/FileCollection.php)  for **uploading** a file

```
$targetList = $context->getWeb()->getLists()->getByTitle("Documents");
$fileCreationInformation = new \SharePoint\PHP\Client\FileCreationInformation();
$fileCreationInformation->Content = file_get_contents($filename);
$fileCreationInformation->Url = basename($filename);
$uploadFile = $targetList->getRootFolder()->getFiles()->add($fileCreationInformation);
$ctx->executeQuery();

```
 

- [`File.openBinary(ClientRuntimeContext $ctx, $serverRelativeUrl)`](https://github.com/vgrem/phpSPO/blob/66395c2091ffbdb3c2551e5e0bcc4d2d5e8dc38b/src/SharePoint/File.php) for **downloading** a file


```
$fileContent = SharePoint\PHP\Client\File::openBinary($context,$fileUrl);
file_put_contents($localPath, $fileContent);

``` 

Follow [`file_examples.php`](https://github.com/vgrem/phpSPO/blob/66395c2091ffbdb3c2551e5e0bcc4d2d5e8dc38b/examples/file_examples.php) for a more examples.

**Comment by rajeshdnws** [comment]
Hi ,
We have used your script to retrieve and update the share point folders and files. could you help me how can we  upload the file in folder 
like I have document library ('Documents') then it 's working fine, now I want to upload it some folder which belong to Documents->foldername

**Comment by evdheuvel** [comment]
@rajeshdnws Did you manage to upload files to a specific folder?

**Comment by rajeshdnws** [comment]
you are  too, late  to reply,
any way thanks, Now I'm able to upload  the file on SharePoint  as per as my requirement
