### ISSUE TITLE
Failed to open autoload_real.php

### ISSUE THREAD

**Issue by svaidyans** [vgrem/phpSPO#47]
Hi Vadim,

Thanks for posting this very useful project!

When I run the ConnectExample.php it is giving:

_"Warning: require_once(.:/phpSPO/phpSPO-master/vendor/composer/autoload_real.php): failed to open stream: No such file or directory in /Users/vsivasubram3/htdocs/phpSPO/phpSPO-master/vendor/autoload.php on line 5

Fatal error: require_once(): Failed opening required '.:/phpSPO/phpSPO-master/vendor/composer/autoload_real.php' (include_path='.:/usr/local/pear/share/pear') in /Users/vsivasubram3/htdocs/phpSPO/phpSPO-master/vendor/autoload.php on line 5"_

I have installed/updated mcrypt and composer successfully, so not sure what the issue is.  Can you please guide me.

Thanks very much,
Vaidya.

**Comment by vgrem** [comment]
Greetings,

try to run:

`composer dump-autoload`

to _re-generate_ the `vendor/autoload.php` file ([docs](https://getcomposer.org/doc/01-basic-usage.md#autoloading))

**Comment by svaidyans** [comment]
Thanks very much for the quick response, Vadim!
It solved the problem.  
However I am now getting "Authentication failed: Direct login to WLID is not allowed for this federated namespace".  I guess this is because the SharePoint Online site I am accessing is a corporate account and we log in with the AD credentials.  Can you please guide me how to get around this issue.

Thanks again,
Vaidya.
