### ISSUE TITLE
How to add an attachment to a list item

### ISSUE THREAD

**Issue by evdheuvel** [vgrem/phpSPO#49]
Hello Vadim,

I'm integrating the phpSPO library in a WordPress plugin. This allows me to publish posts from WordPress to SPO. So far I'm able to create, update and delete posts in SPO. The step I'm struggling with is adding attachments (images and zip files) to the list items in SPO. Below my code, I guess I'm overlooking the obvious. Can you give me a push into the right direction?

Erik

function addPostAttachment(\Office365\PHP\Client\SharePoint\ListItem $item)
{
$attCreationInformation = new \Office365\PHP\Client\SharePoint\AttachmentCreationInformation();
$attCreationInformation->FileName = "foobar.png";
$attCreationInformation->ContentStream = file_get_contents("http://somewebsite/foobar.png");
	
$ctx = $item->getContext();
$item->getAttachmentFiles()->add($attCreationInformation);
$ctx->executeQuery();
}

**Comment by makarandchavan** [comment]
Me too. Please provide one example for attaching a file to list item.
Thanks,
Makarand.

**Comment by vgrem** [comment]
Greetings!

Indeed, it was an issue and it has been resolved. The following simple example demonstrates how to create attachment for a list item:

    $ctx = $list->getContext();
    $itemProperties = array(
        'Title' => 'Order Approval' . rand(1, 1000)
    );
    $listItem = $list->addItem($itemProperties);
    $ctx->executeQuery();


    $attCreationInformation = new AttachmentCreationInformation();
    $path = "../data/SharePoint User Guide.docx";
    $attCreationInformation->FileName = basename($path);
    $attCreationInformation->ContentStream = file_get_contents($path);

    $attachment = $listItem->getAttachmentFiles()->add($attCreationInformation);
    $ctx->executeQuery();
    print "List item attachment url: " . $attachment->getServerRelativeUrl();
