### ISSUE TITLE
Connection failed: Invalid STS request

### ISSUE THREAD

**Issue by lgallard** [vgrem/phpSPO#5]
Hi vgrem,

I got this error:

"Connection failed: Invalid STS request"

The sharepoint I'm trying to connect to has a self-sign certificate. Do I have to do something extra?

Best regards!

**Comment by knox2** [comment]
@lgallard “Invalid STS request” usually comes because either the username or the password contains invalid xml chars (, &, ” or ‘)

**Comment by Portical** [comment]
This could also happen if you do not have:

type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText"

on the Password element of the UsernameToken

**Comment by asila96** [comment]
I'm having the same problem. Username and password don't have invalid characters. 

I am extremely new to Sharepoint, so I could be missing something. 

@Portical - if your comment is the issue, could you explain in newbie's terms what would be needed to fix it?

**Comment by asila96** [comment]
Well, never mind!

When I started tracking through the code, I realized the Password and Username fields were not being passed, because $Settings was not actually being accessed. Ended up re-declaring $Settings in the file I was working with, and then I was able to authenticate

Yay!

**Comment by hi0001234d** [comment]
Yes, @asila96 same with me here the global keyword might not be able to reference to Settings variable if you are deep in classes and name space scope.

**Comment by evolvoltd** [comment]
If your password has special characters it can interfere with XML syntax, please try only alphanumeric password or escape your password.

**Comment by vgrem** [comment]
Propose to close this one since it was determined the root case was either missing user credentials or special characters that needs to be escaped.
