### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by darthk1r1s1ous** [vgrem/phpSPO#51]
Hi,

I'm trying to use the very first example but I'm getting **Class 'AuthenticationContext' not found** despite I load the vendor/autoload.php:

require_once './vendor/autoload.php';
$Url="https://myorganisation.sharepoint.com";
$Username="username";
$Password="password";
$authCtx = new AuthenticationContext($Url);
...
Any idea about what I'm missing?

Installed through Composer.

Thx

**Comment by Gennady-G** [comment]
How You _resolved_?
