### ISSUE TITLE
How to get folders into document library

### ISSUE THREAD

**Issue by darthk1r1s1ous** [vgrem/phpSPO#52]
I'm currently working on listing files and folders on a document library.
I can list all files into root folder with **$list->getRootFolder()->getFiles();**.
But when I use **$list->getRootFolder()->getFolders();** it just return nothing :/

What am I doing wrong?
Thx!

**Comment by vgrem** [comment]
Greetings,

it seems sub folders (`$list->getRootFolder()->getFolders();`) have _not_ been requested from the server, now it is possible to determine whether client object has been retrieved from server as demonstrates the following  example:

 
```
 $folders = $list->getRootFolder()->getFolders();
 if($folders->getServerObjectIsNull() == true){  //determine whether folders has been loaded or not
      $ctx->load($folders); //prepare a query to load a folders collection 
      $ctx->executeQuery(); //submit a query to the server
 }
 foreach ($folders->getData() as $folder) {
     print "File name: '{$folder->Name}'\r\n";
 }
```
