### ISSUE TITLE
Download files from subfolder

### ISSUE THREAD

**Issue by ejvg84** [vgrem/phpSPO#53]
Hi, i am trying to download files inside a subfolder like "Documents/FolderA/file.xls" and i can find any example how to do it.

I am using your file_examples.php as a guide but when a change $targetLibraryTitle to Documents/FolderA the files cant find the folder (it exists, i cant access ir by web browser).

Any example or help?

**Comment by vgrem** [comment]
The following example demonstrates how to download a file from a folder:


```
$fileContent = Office365\PHP\Client\SharePoint\File::openBinary($ctx,$fileUrl);
file_put_contents($targetFilePath, $fileContent); 
```

where 

- `$ctx` - `ClientContext` object

- `$fileUrl` - the url of file to download in the following format: `/site/documents/folder/file.txt  ` 

- `$targetFilePath` - the file to write to
