### ISSUE TITLE
Is it possible to add a document library?

### ISSUE THREAD

**Issue by Rojandev** [vgrem/phpSPO#57]

**Comment by vgrem** [comment]
The following example demonstrates how to create a Documents library:

    $info = new ListCreationInformation("My Documents");
    $info->Description = "My Documents library";
    $info->BaseTemplate = \Office365\PHP\Client\SharePoint\ListTemplateType::DataConnectionLibrary;
    $list = $ctx->getWeb()->getLists()->add($info);
    $ctx->executeQuery();
