### ISSUE TITLE
How to create a folder in a Document Library?

### ISSUE THREAD

**Issue by josepichu** [vgrem/phpSPO#58]
HI !
 
Im trying to create a Folder in my Document Library called **Tfts**. 
I'm ussing this code
**eiic** and **2017** folders are already create. My goal is to create **test** folder.

```
	$authCtx = new AuthenticationContext($Settings['Url']);
	$authCtx->acquireTokenForUser($Settings['UserName'],$Settings['Password']);  
        $folderUrl = "Tfts/eiic/2017/test";

    $url = $Settings['Url'] . "/_api/web/folders";
    $request = new RequestOptions($url);
    $ctx = new ClientContext($url,$authCtx);
  
    $itemPayload = array( 
        '__metadata' => array ('type' => 'SP.Folder', 'ServerRelativeUrl' => $folderUrl)
        );

    $request->addCustomHeader("If-Match", "*");
    $request->Data = $itemPayload;
    $request->Method = 'POST';
    $data = $ctx->executeQueryDirect($request);
    var_dump($data);
```
I had the following error:
```
**Notice: Array to string conversion in C:\wamp64\www\phpSPO\src\Runtime\Utilities\Requests.php on line 111
Warning: strlen() expects parameter 1 to be string, array given in C:\wamp64\www\phpSPO\src\Runtime\Utilities\Requests.php on line 112**
```
the dump content:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
```

Thank u very much :) !

**Comment by blizzz** [comment]
According to  the error message, you miss a content length header.

Why don't you work against the  FolderCollection, which provides an add() method? E.g.:

```php
$relativeServerPath = '/Document Library Name/Some Folder/Another Folder/New Folder';
$parentFolder = $ctx->getWeb()->getFolderByServerRelativeUrl(dirname($relativeServerPath));
$folder = $parentFolder->getFolders()->add(basename($relativeServerPath));
$ctx->executeQuery();
```

**Comment by josepichu** [comment]
Thanks @blizzz, Its works perfectly !

you can close this thread.

**Comment by blizzz** [comment]
> Thanks @blizzz, Its works perfectly !

You're welcome!

> you can close this thread.

@vgrem your turn

**Comment by sargearmstrong** [comment]
Dears - I know this thread is closed and I apologize for posting on it, but I have a related problem - kindly advise (by the way, thank you for phpSPO).

When running the renameFolder.php example, I get the same strlen expects parameter 1... (blah blah) for the following line 117 in Requests.php:
`$options->addCustomHeader("content-length",strlen($options->Data));`

If I attempt the following changes:
`$options->addCustomHeader("content-length", mb_strlen(serialize((array)$options->Data), '8bit'));`
or
`$options->addCustomHeader("content-length", 152);`


...renameFolder.php runs for a minute or two before timing out with the following error: Error: OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104

If I comment out this line 117, then renameFolder.php completes almost instantly (with no error) but without renaming the target folder on sharepoint365. So, I assume the content-length header is required but if incorrect.. the call hangs. Any clarification how to handle this would be much appreciated, thanks!

Contents of $results after populating $itemPayload:
![image](https://user-images.githubusercontent.com/4032997/57039854-a120c000-6c12-11e9-80d0-7276198aa7bb.png)
