### ISSUE TITLE
How to create folder inside of a folder? 

### ISSUE THREAD

**Issue by Rojandev** [vgrem/phpSPO#60]

**Comment by vgrem** [comment]
Let's say your site has the following structure:

    Documents library 
    |
    ---   Achive folder  


then the example below shows how to create a child folder named `2001` under `Archive` folder:

    $folderName = ""2001";
    $targetFolderUrl = "/Documents/Archive";
    $parentFolder = $ctx->getWeb()->getFolderByServerRelativeUrl($parentFolderUrl);
    $childFolder = $parentFolder->getFolders()->add($folderName);
    $ctx->executeQuery();
    print "Child folder {$childFolder->getProperty("ServerRelativeUrl")} has been created ";
