### ISSUE TITLE
Error using filter

### ISSUE THREAD

**Issue by suparsana21** [vgrem/phpSPO#69]
Hello, i want to get data using filter() but i get some error
`$nik = '5171041305650002';`
`$items = $list->getItems()->filter("NIK eq '$nik'");`
`$itemdata = $items;  //prepare a query to retrieve from the `
`$ctx->load($items);  //save a query to retrieve list items from the server `
`$ctx->executeQuery(); //submit query to SharePoint Online REST service `

but i get error like this 

> <b>Fatal error</b>:  Uncaught exception 'Exception' with message 'The operation tried prevented therefore exceeds the list view threshold imposed by the administrator.' in C:\AppServ\www\phpSPO\src\Runtime\ClientRequest.php:186
Stack trace:
#0 C:\AppServ\www\phpSPO\src\Runtime\ClientRequest.php(138): Office365\PHP\Client\Runtime\ClientRequest-&gt;validateResponse('{&quot;error&quot;:{&quot;code...')
#1 C:\AppServ\www\phpSPO\src\Runtime\ClientRuntimeContext.php(133): Office365\PHP\Client\Runtime\ClientRequest-&gt;executeQuery()
#2 C:\AppServ\www\phpSPO\src\SharePoint\ClientContext.php(83): Office365\PHP\Client\Runtime\ClientRuntimeContext-&gt;executeQuery()
#3 C:\AppServ\www\phpSPO\app\data_ktp.php(25): Office365\PHP\Client\SharePoint\ClientContext-&gt;executeQuery()
#4 {main}
  thrown in <b>C:\AppServ\www\phpSPO\src\Runtime\ClientRequest.php</b> on line <b>186</b><br />

**Comment by vgrem** [comment]
Greetings!

The specified error occurs 


Please refer this

**Comment by vgrem** [comment]
[](url)
