### ISSUE TITLE
Could not resolve host: login.microsoftonline.com

### ISSUE THREAD

**Issue by dotjsprogrammer** [vgrem/phpSPO#80]
Here's the complete error message:

`PHP Fatal error:  Uncaught exception 'Exception' with message 'Could not resolve host: login.microsoftonline.com' in /var/www/properties/web/spo/src/Runtime/Utilities/Requests.php:34
Stack trace:
#0 /var/www/properties/web/spo/src/Runtime/Utilities/Requests.php(67): Office365\\PHP\\Client\\Runtime\\Utilities\\Requests::execute(Object(Office365\\PHP\\Client\\Runtime\\Utilities\\RequestOptions))

#1 /var/www/properties/web/spo/src/Runtime/Auth/SamlTokenProvider.php(92): Office365\\PHP\\Client\\Runtime\\Utilities\\Requests::post('https://login.m...', NULL, '???<s:Envelope ...')

#2 /var/www/properties/web/spo/src/Runtime/Auth/SamlTokenProvider.php(60): Office365\\PHP\\Client\\Runtime\\Auth\\SamlTokenProvider->acquireSecurityToken('testuser@site.sharepoint.com', 'p@ssword')

#3 /var/www/properties/web/spo/src/Runtime/Auth/AuthenticationContext.php(69): Office365\\PHP\\Client\\Runtime\\Auth\\SamlTokenProvider->acquireToken(Array)

#4 /var/www/properties/web/spo/index.php(11): Office365\\PHP\\Client\\Runtime\\Auth\\AuthenticationContext->ac in /var/www/properties/web/spo/src/Runtime/Utilities/Requests.php on line 34`

For context, **site.sharepoint.com** is my employer's SharePoint online site. Assuming the URL and credentials are correct, what else am I missing?

**Comment by syl666** [comment]
Did you ever resolve this one?

**Comment by cweiske** [comment]
The system running phpSPO is not able to resolve the IP for the DNS entry `login.microsoftonline.com`, which is not something that can be fixed by phpSPO.

Using `ping login.microsoftonline.com` or `host login.microsoftonline.com` will yield the same problem.

You have to fix your DNS settings.

@vgrem please close.
