### ISSUE TITLE
Getting warning and unable to print the list data

### ISSUE THREAD

**Issue by chetank25** [vgrem/phpSPO#84]
I am using the following code to print the list items as per the list_examples.php file but getting an error, I am using SAML to authenticate.

$authCtx = new AuthenticationContext($Settings['Url']);
$authCtx->acquireTokenForUser($Settings['UserName'],$Settings['Password']);
$ctx = new ClientContext($Settings['Url'],$authCtx);

printLists($ctx);

function printLists(ClientContext $ctx){
    $lists = $ctx->getWeb()->getLists();
	
	$ctx->load($lists);
	$ctx->executeQuery();
	
	var_dump($lists->getData());
	
	foreach( $lists->getData() as $list ) {
	    print "List title: '{$list->Title}'\r\n";
	}
}

Error:

Warning: First parameter must either be an object or the name of an existing class in C:\xampp\htdocs\phpspo\vendor\vgrem\php-spo\src\Runtime\OData\ODataPayloadSerializer.php on line 52

Warning: First parameter must either be an object or the name of an existing class in C:\xampp\htdocs\phpspo\vendor\vgrem\php-spo\src\Runtime\OData\ODataPayloadSerializer.php on line 55

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\phpspo\vendor\vgrem\php-spo\src\Runtime\ClientObjectCollection.php on line 265
array(0) { }

**Comment by vgrem** [comment]
Greetings,

it seems you are utilizing the version which either not the latest or not the stable one.
I would propose to get the latest version, in that case the specified errors should no longer occur.

**Comment by chetank25** [comment]
Hi Vgerm,

Thanks for getting back to me!

I am using  PHP 5.6.3 (cli) (built: Nov 12 2014 17:18:08). 

As per you read me file it  says "PHP 5.4 or later", so I do have later version. 

Regards

Chetan
