### ISSUE TITLE
MoveTo/copyTo

### ISSUE THREAD

**Issue by rophini** [vgrem/phpSPO#89]
Hi,

I can't copy/move a file. This is the code I'm using:

$spFiles = $ctx->getWeb()->getFolderByServerRelativeUrl(/site/Documents/Testing/New)->getFiles();
$ctx->load($spFiles);
$ctx->executeQuery();
$files = $files->getData();
foreach($files as $file) {
   $file->copyTo('/site/Documents/Testing/Processing', true);
}

Am I doing something wrong? Thanks

**Comment by vgrem** [comment]
Greetings!

In addition to:
`$file->copyTo('/site/Documents/Testing/Processing', true);`
which constructs the query for copying a file, the following command is missing: 
`$ctx->executeQuery();  ` 
that basically tells to submit the query to the server



**Modified example**

```
$spFiles = $ctx->getWeb()->getFolderByServerRelativeUrl(/site/Documents/Testing/New)->getFiles();
$ctx->load($spFiles);
$ctx->executeQuery();
$files = $files->getData();
foreach($files as $file) {
    $file->copyTo('/site/Documents/Testing/Processing', true);
    $ctx->executeQuery();  //submits query to the server 
}

```
