### ISSUE TITLE
Filter on taxonomy field value

### ISSUE THREAD

**Issue by CedricG87** [vgrem/phpSPO#92]
Hello,

Great library. I was just wondering how can I filter on taxonomy field ? I have a field named "Languages" and would like to only search for specific value (ex: "FR").

I tried this :
` $query = new \Office365\PHP\Client\SharePoint\CamlQuery();
$query->ViewXml="<View><Query><Where><Contains><FieldRef Name='Languages'/><Value Type='Text'>FR</Value></Contains></Where></Query></View>";
$items = $list->getItems($query);`

It doesn't work maybe I'm doing it wrong?

**Comment by shoyheim** [comment]
Hi,
I'm also having this problem, can't get any camlquery to work.
My last attemt was this:

`$list = $web->getLists()->getByTitle($this->listTitle); `
        `$items = $list->getItems(CamlQuery::createAllFoldersQuery());  `
        `$ctx->load($items);`
        `$ctx->executeQuery();`

But this still return every folder and file in the list...
I've also tried several version of self created CamlQueries, but no luck, I get the same result, or if I write something to make my CamlQuery invalid, I get an empty result.

This really seems like a bug to me.

**Comment by shoyheim** [comment]
I just now detected that if call it like this (omitting the load) it works... but then I'm not able to add a field selection, since I need the load to do that...

`$list = $web->getLists()->getByTitle($this->listTitle);`
`$items = $list->getItems(CamlQuery::createAllFoldersQuery());`
`$ctx->executeQuery();`

**Comment by vgrem** [comment]
Greetings!

Indeed, when specifying  CAML  along with retrieval method (`load`), the first one was ignored, thank you @shoyheim and @CedricG87 for providing those examples and details, was able to reproduce it.  

In the [latest version](https://github.com/vgrem/phpSPO/tree/v2.3.0) this issue has been resolved and the following queries should work as expected:



```
#retrieve items via CAML query
$list = $web->getLists()->getByTitle($listTitle);
$items = $list->getItems(CamlQuery::createAllFoldersQuery());
$client->load($items);
$client->executeQuery();

```

```
#retrieve items by combining CAML query and query options operators
$list = $web->getLists()->getByTitle($listTitle);
$items = $list->getItems(CamlQuery::createAllFoldersQuery())
                         ->select("Predecessors/Title")
                         ->expand("Predecessors")
                         ->filter("FSObjType eq 0");
$client->load($items);
$client->executeQuery();

```


```
#retrieve specific field values via items method
$list = $web->getLists()->getByTitle($listTitle);
$items = $list->getItems();
$client->load($items, ["Title"]);
$client->executeQuery();

```

**Comment by balusreekanth** [comment]
If you use $client->load($items) then it loads all entries . For single entry This is working for me .

$web = $client->getWeb();
$list = $web->getLists()->getByTitle("Product Master");
$qry = new CamlQuery();
$xml = '<View><Query><Where><Eq><FieldRef Name="Title" LookupId="TRUE"/><Value Type="Text">QatarAirways</Value></Eq></Where></Query></View>';
$qry->ViewXml = $xml;
$items = $list->getItems($qry);
$client->executeQuery();

 print($items->getCount() .PHP_EOL);

 foreach ($items as $index => $item){
    print($index . ":" . $item->getProperty('Title') . PHP_EOL);
}
