### ISSUE TITLE
SharePoint getItems() CamlQuery Bug

### ISSUE THREAD

**Issue by dk2103** [vgrem/phpSPO#95]
While trying CAML queries to filter Items a complete Set auf Items is returned. That's most likely caused by a parsing error in ODataRequest's buildRequest() or normalizePayload() method. 

$request->Data is:
```
string(351) "{"query":
                      {"ViewXml": "\r\n \r\n \r\n \r\n \r\n test<\/Value>\r\n <\/Eq>\r\n <\/Where>\r\n <\/Query>\r\n "
                      ,"__metadata":
                           {"type":"SP.CamlQuery"}}}"
```

but should be like(?):
```
{ "query" :
   {"__metadata": 
      { "type": "SP.CamlQuery" }
      , "ViewXml": "<YOUR CAML QUERY>"
   }
}
```

If I'm wrong is there another way to use CamlQuery?

**Comment by vgrem** [comment]
Greetings!

the valid payload format for `getItems `method should look like this:

```
{
         "query":
          {
              "ViewXml": "<View></View> ",
                "__metadata":   {"type":"SP.CamlQuery"}
          }
} 
```


The reason why the query is getting _ignored_ in your case is related with **invalid** CAML query specified via [ViewXml ](https://msdn.microsoft.com/en-us/library/microsoft.sharepoint.client.camlquery.viewxml(v=office.14).aspx) property:

`\r\n \r\n \r\n \r\n \r\n test<\/Value>\r\n <\/Eq>\r\n <\/Where>\r\n <\/Query>\r\n`


The **valid** `ViewXml  `property should look like this:

```
<View><Query><Where><Eq><FieldRef Name='Title'/>" +
                "<Value Type='Text'>10</Value></Eq></Where></Query><RowLimit>100</RowLimit></View>

```

### References

[How to: Retrieve List Items](https://msdn.microsoft.com/en-us/library/office/ee534956(v=office.14).aspx)
