### ISSUE TITLE
Support of proxy

### ISSUE THREAD

**Issue by wihab01** [vgrem/phpSPO#99]
As far as I have seen, the library does not support calls to SPO via proxy. Is it possible to use this library without modification from behind a firewall?
Because of an urgent request I have solved it by modifying the library code and can provide a Pull Request if that is wished.

**Comment by yanikore** [comment]
It also makes debugging easier because you can use Fiddler to inspect the traffic.

**Comment by crealistiques** [comment]
@wihab01 I have an urgent request now too ;) Are you able to provide a pull request or send me your modified code as a whole by email. That would be great! Thanks in advance and have a good time.

**Comment by yanikore** [comment]
@crealistiques If you want to edit the library code you can add the following line to the curl init wrapper function in Requests.php:
```
curl_setopt($ch, CURLOPT_PROXY, '127.0.0.1:8888');
```
https://github.com/vgrem/phpSPO/blob/master/src/Runtime/Utilities/Requests.php#L94
